 == O InnerSource é adequado para o meu projeto?

InnerSource é a aplicação dos princípios de código aberto ao desenvolvimento de software interno da empresa. Feito corretamente, desbloqueia o progresso e facilita a adoção de serviços e módulos compartilhados.
Este artigo contém orientações e perguntas a serem feitas ao considerar a adoção de uma abordagem InnerSource para executar seu projeto.

=== As contribuições virão?

Uma abordagem InnerSource só faz sentido se forem esperadas contribuições dos usuários do projeto.
Você pode esperar contribuições se vir ou antecipar quantidades perceptíveis de energia direcionada à área do seu projeto por seus usuários. Alguns exemplos:

* Altas quantidades de uso e adoção de projetos.
* Mais solicitações de recursos do que sua equipe tem tempo para atender.
* Usuários fazendo soluções alternativas para compensar a falta de recursos em seu projeto.
* Solicitações de recursos que levam quase tanto tempo para serem explicadas quanto para serem implementadas.
* Múltiplas dependências de roteiro em seu projeto.

=== Vou apoiar contribuições?

Mesmo com colaboradores dispostos, o código não flui.
Você precisará encorajar e apoiar contribuições por meio de atividades como:

* Compreender os cenários dos usuários e sugerir quais contribuições em seu projeto podem ajudá-los a atender a esses cenários.
* Convidar os usuários a fazer as contribuições de que precisam e acompanhá-los para garantir que o façam.
* Manter um documento https://patterns.innersourcecommons.org/p/base-documentation#contributing.md[CONTRIBUTING.md] que contém tudo o que um engenheiro precisa saber para contribuir com o projeto.
* Dando orientação e direção inicial sobre como implementar uma determinada contribuição.
* Estar disponível durante o horário regular para quaisquer perguntas ad hoc que os contribuidores tenham.
* Revisão oportuna dos pull requests recebidos.
* Manutenção contínua do código enviado (após https://patterns.innersourcecommons.org/p/30-day-warranty[janela de garantia]).

=== É específico da empresa?

Os projetos InnerSource fazem sentido quando o projeto é específico para a empresa ou quando seu uso exclusivo dá à empresa uma vantagem estratégica de negócios.
Outros projetos colaborativos devem ser executados como código aberto para aumentar o pool de contribuição e o impacto.

=== Resumo

Se as contribuições vierem *e* você apoiar essas contribuições *e* seu projeto for específico da empresa, então a InnerSource é a certa para o seu projeto.