== Sicherstellung der Produktqualität

Lasst uns mit der wohl am öftesten mit der Rolle des _Trusted Committers_ in 
Verbindung gebrachten Verantwortung beginnen: der Sicherstellung der Produktqualität.

In einer _InnerSource_-Organisation sind die _Trusted Committers_ verantwortlich für
alle technologisch basierten Entscheidungen, speziell derjenigen, die sich auf die Produktqualität beziehen.
Verantwortlichkeit in diesem Fall bedeutet die Notwendigkeit, sicherzustellen, dass diese Entscheidungen
respektiert werden. Das schließt die Kommunikation dieser Entscheidungen und - falls notwendig - deren Verfechtung
 innerhalb und außerhalb der Organisationseinheit mit ein. Das bedeutet aber nicht, dass infolge alle technologisch
basierten Entscheidungen von den _Trusted Commiters_ getroffen werden müssen, noch dass diese die komplette 
Implementierungsarbeit erledigen.

Die Aufgabe eines _Trusted Committers_ ist es, die Qualitätsstandards innerhalb ihrer Organisation zu kommunizieren 
und zu erläutern, vor allem aber sie so zu formulieren, dass sie für ihre https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_]
verständlich und anwendbar sind. Dies beinhaltet natürlich auch die schriftliche Dokumentation, aber es ist für eine _InnerSource_-Organisation der effektivste Weg 
diese Standards vorzuleben und Beispiele zu geben. 
Wir glauben, dass es ein erstrebenswertes Ziel für eine _InnerSource_-Organisation sein sollte, sich nicht nur in der Arbeitsmethodik
 von einer klassischen Entwicklungsorganisation zu unterscheiden, sondern auch in der Qualität der Software, die sie entwickelt. Softwarequalität auf höchstem 
Niveau ist eine Grundvoraussetzung, um Vertrauen seitens des Managements und der Benutzer in eine  _InnerSource_-Organisationeinheit aufzubauen 
und aufrecht zu erhalten. Wir alle wissen, wie schnell dieses Vertrauen durch eine einzige fehlerhafte Auslieferung erschüttert werden kann.

_Trusted Committers_ stellen außerdem sicher, das in der Organisation die notwendige Infrastruktur und die notwendigen Tools vorhanden sind, welche zur Entwicklung qualitativ 
hochwertiger Software benötigt werden.
Zur Sicherstellung der Qualität wird am häufigsten das _Peer Review_ genutzt, welches normalerweise Bestandteil der Pull Requests (PR's) ist.
 Während für gewöhnlich jedermann Pull Requests starten und daran teilnehmen kann, indem er auf notwendige 
Verbesserungen hinweist, ist es normalerweise nur dem _Trusted Committer_ möglich, Beiträge zu akzeptieren oder abzulehnen.
Das ist es, was wir an anderer Stelle damit gemeint haben, wenn wir davon sprachen, dass "_Trusted Committers_ näher an der Freigabe des Codes sind". 
 _Trusted Committers_ sollten den https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_] auch während eines PR's helfen,
ihre Beiträge fertig zu stellen.

Dennoch ist es letztendlich die Aufgabe des _Contributors_, dies zu erreichen.
Es ist nicht Aufgabe eines _Trusted Committers_, alle Beiträge grundsätzlich zu akzeptieren, sondern nur diejenigen, die die definierten Kriterien bezüglich Qualität und Umfang erfüllen. 
Und _Trusted Committers_ sollten vermeiden, den Code eines _Contributors_ umzuschreiben, um ihn passend zu machen, selbst wenn dadurch ein höherer Aufwand bei der Betreuung des 
https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_] während eines PR's entsteht. _Trusted Committers_
nehmen eine längerfristige Perspektive ein und verstehen, dass diese Art der Unterstützung eine Investition in die Langlebigkeit der Organisation darstellt, 
und dies langfristig die Entwicklungsgeschwindigkeit der Organisation erhöht.

Manchmal sind Anforderungen und Einschränkungen des Projekts nicht von vorne herein bekannt, sondern werden erst während der Entwicklung erkannt.
_Trusted Committers_ sind auch dafür verantwortlich, dass diese Ergebnisse erfasst und dokumentiert werden, so dass diese sowohl 
den https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/01-opening-article.asciidoc[_Product Owners_] als auch den 
https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_] zugänglich sind.

Aber der Aufgabenbereich des _Trusted Committers_ in Bezug auf Qualität geht über Pull Requests hinaus. 
_Trusted Committers_ betrachten Qualität als strategische Komponente und stellen die Langlebigkeit der zu erstellenden Software sicher. Dies beinhaltet codeorientierte Verantwortlichkeiten im Sinne von _clean code_ bis hin zur
Wahrung der konzeptionellen Integrität der gesamten Software.
Dazu gehören auch managementorientierte Aufgaben, wie zum Beispiel sicherzustellen, dass die Organisation genügend Zeit für Pflege der Software hat, oder wenn nötig, die Verschiebung von Bereitstellungsterminen 
zugunsten der Verbesserung der Softwarequalität zu veranlassen.
Der Effektivität des _Trusted Committer_ basiert stark auf der Wartbarkeit des Code's ab.

Fehlt letzteres, müssen die _Trusted Committers_ viel ihrer wertvollen Zeit investieren, um Workarounds für Fehler oder anfällige Architektur zu validieren und zu dokumentieren. Dadurch haben sich nicht 
ausreichend Zeit, um https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_] einzubeziehen und zu betreuen.

Zusammengefasst ist das Sicherstellen der Produktqualität eine Schlüsselverantwortung eines _Trusted Committers_.
Sie bestimmen die Qualitätsstandards und gehen mit gutem Vorbild voran. Sie unterstützen bei Pull Requests und helfen den 
https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.asciidoc[_Contributors_] die Qualitätsstandards zu erfüllen. 
Sie übernehmen auch die Verantwortung für die langfristige Wartbarkeit und Qualität der Software. 

