== Die Leistungsfähigkeit der Organisation erhalten

In der Einführung wurde darauf hingewiesen, dass _Trusted Committer_ sowohl technikorientierte als auch organisationsorientierte Verantwortlichkeiten haben. Es ist nicht ausreichend, sich nur auf den _Code_ und den Zustand des _Codes_ zu konzentrieren. 
Um auf lange Sicht erfolgreich zu sein, sollten _Trusted Committer_ auch danach streben, die Community, die die Software erstellt, gesund zu erhalten. Deshalb müssen sie sich um eine gute Balance zwischen dem Sicherstellen der Produktqualität und dem Wachstum der eigenen Community bemühen.

Was macht eine gute Community aus? Sehr einfach, eine gute Community motiviert die https://innersourcecommons.org/resources/learningpath/contributor/index[_Contributors_] dazu dabeizubleiben, sie können den Großteil ihrer Zeit für die Entwicklung der Software einsetzen, und sind in der Lage, ihre Fähigkeiten zu verbessern. 
Infolgedessen wird sich eine gute Community kontinuierlich wachsen.

Warum schließen sich https://innersourcecommons.org/resources/learningpath/contributor/index[_Contributors_] einer Community an und bleiben dabei? Einige tun dies, weil sie sich mit dem Zweck der Community identifizieren können.
Es ist die Aufgabe der _Trusted Committer_, diesen Zweck klar zu formulieren und fördern. Dessen Bedeutung wird oft nicht erkannt, aber Marketing für die Community und ihrer Produkte ist tatsächlich entscheidend.

Ein weiterer, offensichtlicher Grund für jemanden dabeizubleiben ist die Zusammenarbeit mit anderen Community Mitgliedern. 
Dies schließt die _Trusted Committer_ mit ein. 
In einer erfolgreichen Community kommunizieren und behandeln sich die Mitglieder mit höchstem gegenseitigen Respekt. 
Beiträge werden mehr als Geschenke oder Spenden denn als Ablenkungen behandelt, und sehr gute Beiträge (insbesondere erste) werden gelobt. 
Die Aufgabe der _Trusted Committer_ besteht in erster Linie darin, ein Vorbild für andere zu sein, analog zu einem Vorbild bezüglich der erwarteten Softwarequalität. 
Falls notwendig, sollten die _Trusted Committer_ einen Code of Conduct beschließen und durchsetzen. 
Falls sich Mitglieder der Community schädigend verhalten, ist es die Aufgabe der _Trusted Committer_, dies zu adressieren. _Trusted Committer_ sollen regelmäßige Treffen für Mitglieder anbieten (entweder persönlich oder virtuell). Dabei können sich Teilnehmergegenseitig kennenlernen und auftretende Konflikte einvernehmlich zu lösen sobald sie auftreten.

Menschen neigen auch dazu sich an Projekten zu beteiligen, weil die Mitarbeit in einer _InnerSource Community_ eine hervorragende Gelegenheit bietet neue Fähigkeiten zu erlernen und als Person zu wachsen. 
Dies ist ein weiterer Aspekt, in dem die Rolle des _Trusted Committers_ wirklich wichtig ist. 
_Trusted Committer_ sind oft Mentoren für jüngere Entwickler, und verwenden Zeit während der Pull Requests, um nicht nur auf Verbesserungspotentiale hinzuweisen, sondern auch im Detail zu erklären, warum und wie etwas verbessert werden muss. 
Sie liefern die Theorie oder das Hintergrundwissen zu Verbesserungen und schlagen die besten Möglichkeiten vor Änderungen oder Verbesserungen zu implementieren. Dadurch können _Trusted Committer_ die Lerngeschwindigkeit ihrer Organisation weit über die traditioneller Software-Entwicklungsorganisationen erhöhen.

Wir glauben, dass _Trusted Committer_ das Anwerben und Betreuen während der Pull Requests über das Erreichen von Veröffentlichungsterminen stellen sollten, außer es sprechen triftige Gründe dagegen. 
Gute Betreuung während eines Pull Requests führt zu höherem Vertrauen und Einbindung von https://innersourcecommons.org/resources/learningpath/contributor/index[_Contributors_], was im Gegenzug zu mehr Mitarbeit führt. 
Wir werden diesen Aspekt in https://innersourcecommons.org/resources/learningpath/trusted-committer/04/["Upleveling the Community"] näher betrachten.

Schliesslich gibt es Menschen, die sich in _InnerSource Communities_ engagieren, weil sie sich dort auf das Entwickeln von Software konzentrieren können anstatt anderen Aufgaben nachzugehen, die häufig als überflüssig oder unnötig angesehen werden. 
Dies trifft häufig auf große Unternehmen mit einem starken Fokus auf Prozesse zu. 
Die Aufgabe der _Trusted Committer_ in diesem Zusammenhang ist es, sicherzustellen dass die https://innersourcecommons.org/resources/learningpath/contributor/index[_Contributors_] sich auf ihre Projekte konzentrieren können, indem sie sinnvolle Contribution Guidelines kommunizieren und einsetzen.

Ein wichtiger Aspekt dieser Guidelines ist, was wir in Pull Requests  _signaling_ nennen: Wie soll ein Kommentar aussehen? 
Was bedeutet es, wenn ich einen Kommentar "_like_" oder "_+1_" vergebe? Wie unterscheidet sich beim _@mentioning_ die Verwendung eines _/CC_-Vorzeichens von einem _/FYI_-Vorzeichen? 
Allgemein gesprochen müssen _Trusted Committer_ sicherstellen, dass der Prozess, im Projekt mitzuarbeiten, nicht mehr Probleme verursacht, sondern die Community unterstützt Probleme im Projekt zu identifizeren und zu lösen. 
Schließlich sollten _Trusted Committer_ ihre Community dazu befähigen, prozessbezogene Probleme zu finden und diese so gut wie möglich selbst anzupassen und zu verbessern.

Damit _Trusted Committer_ alle diese Verantwortlichkeiten erfüllen können, ist es wichtig, dass sie regelmäßig mit den Mitgliedern der Community kommunizieren und ein Gespür für die allgemeine Stimmung entwickeln. 
Wir werden dies näher im Kapitel https://innersourcecommons.org/resources/learningpath/trusted-committer/06/["Advocating the Community's Needs"] betrachten.

Zusammengefasst sollten _Trusted Committer_ sich bemühen ein einladendes und annerkennendes Umfeld für ihre https://innersourcecommons.org/resources/learningpath/contributor/index[_Contributors_] zu erzeugen, welches diesen erlaubt, sich auf das Schreiben von Software zu konzentrieren und ihre Persönlichkeit weiterzuentwickeln indem sie von anderen Mitgliedern der Organisation lernen.
