
[[advocating]]
== Für die Belange der Community eintreten


InnerSource Communities existieren im Kontext eines Unternehmens und unterliegen daher größeren Einschränkungen als Open Source Communities. Manchmal stehen die Interessen des Unternehmens im Widerspruch zu denen der Community. Trusted Committer vertreten eine langfristige Perspektive für ihr Projekt. Sie verstehen, dass eine funktionierende Gemeinschaft eine Vorbedingung für die langfristige Wartbarkeit und Qualität der Software ist. Aus diesem Grund sind viele InnerSource Initiativen nach dem Apache Motto modelliert: http://theapacheway.com/community-over-code/["Community over Code"]. Unternehmen hingegen befassen sich natürlich mehr mit den Produkten selbst, die von der InnerSource Community entwickelt werden. Sie bevorzugen kurz- bis mittelfristige Ergebnisse, die die Geschäftsziele verbessern.

Daraus ergibt sich ein möglicher Konflikt, in welchem _Trusted Committer_ eine wesentliche Rolle spielen.
_Trusted Committer_ generieren Vertrauen im Unternehmen und agieren, aufbauend auf dieses Vertrauen, als Interessensvertreter für die Community und die langfristige Wartbarkeit und Qualität der Software im Unternehmen.
Sie sind dafür verantwortlich, dass sowohl technische als auch organisatorische Risiken an das Management berichtet werden. 
Gleichzeitig müssen _Trusted Committer_ strategisch handeln und sich innerhalb der vom Unternehmen gebotenen Freiheiten bewegen.

_Trusted Committer_ müssen sich auch darum kümmern, dass die Community und einzelne https://innersourcecommons.org/learn/learning-path/contributor/01[Contributors] öffentliche Anerkennung für Ihre Arbeit erhalten. Öffentliche Anerkennung ist die Währung, mit der Contributors belohnt werden, speziell diejenigen, die freiwillig beitragen. Es hat sich bewährt, wertvolle Contributors öffentlich zu loben und sicherzustellen, dass ihre Führungskraft über ihre Beiträge informiert werden. Beiträge nicht zu loben kann für die jeweiligen Contributors frustrierend sein und wirkt sich negativ auf die Community aus. So etwas kann in Unternehmen passieren, die noch nicht an das InnerSource-Arbeitsmodell gewöhnt sind, oder wenn die von der InnerSource-Community entwickelte Software hinter den Kulissen ausgeführt wird und das Management die Beitrage der Community einfach nicht kennt.
Ein guter _Trusted Committer_ arbeitet mit dem Management zusammen und setzt sich dafür ein, Erfolge zu feiern. Erfolge nicht zu feiern geschieht in den meisten Fällen nicht aus böser Absicht und ist einfach zu beheben.

Ein anderer Fall, der die Vermittlung des _Trusted Committers_ erfordert, ist wenn https://innersourcecommons.org/learn/learning-path/contributor/01[Contributors] keine Zeit oder Erlaubnis bekommen, an der Community mitzuarbeiten.
Dies kann passieren, wenn die Community an Produkten ausserhalb des Verantwortungsbereichs des _Contributors_ arbeitet und diese nicht relevant für die Ziele der jeweiligen Untereinheit im Unternehmen sind. 
In diesem Fall sollte der _Trusted Committer_ das Gespräch mit der Führungskraft des _Contributors_ suchen und sich für eine andere Entscheidung einsetzen.

Zusammengefasst gibt es viele Situationen, in denen sich der _Trusted Committer_ für die Interessen der einzelnen https://innersourcecommons.org/learn/learning-path/contributor/01[Contributors] und für das Unternehmen als ganzes einsetzen sollte.
_Trusted Committer_ verstehen, dass der Wert, den die Community für das Unternehmen bieten kann, von einer funktionierenden und langlebigen Community und letztendlich von einer vertrauenswürdigen Beziehung zwischen Unternehmen und Community abhängt.


