== Wie wird man ein _Trusted Committer_

Die Rolle des _Trusted Committer_ ist zwar anspruchsvoll, aber auch erfüllend. Wenn dich dieses Tutorial interessiert, dann möchtest du vielleicht wissen, wie man zu einem _Trusted Committer_ wird, und ob du die richtige Person für diese Aufgabe bist.

InnerSource Communities funktionieren nach denselben Prinzipien wie Open Source Communities, eines davon ist Meritokratie. In einer Meritokratie wird Ansehen basierend auf Talent, Anstrengung und Erreichtem erworben. Das bedeutet, dass das Ansehen und Privilegien, die mit der Rolle des _Trusted Committers_ einhergehen, verdient werden müssen. 
Transparenz, ein weiterer Wert von Open Source, spielt ebenfalls eine wesentliche Rolle dabei, Talent, Anstrengung und Erreichtes in der gesamten Gemeinschaft sichtbar zu machen. 

Der Prozess, offiziell ein _Trusted Committer_ zu werden, unterscheidet sich von Community zu Community und hängt davon ab, wo du persönlich in deiner Inner Source Reise stehst und wird sich im Lauf der Zeit entwickeln. In neu gegründeten Communities übernehmen die Gründer oft selbst die Rolle des _Trusted Committers_. Wenn die Community dann wächst, oder in größeren Communities, werden _Trusted Committer_ normalerweise nominiert oder von den https://innersourcecommons.org/resources/learningpath/contributor/index[Contributors] der Community gewählt.
Trotzdem sollte die Rolle des _Trusted Committers_ freiwillig übernommen werden, denn sie erfordert großen Zeitaufwand und Engagement um erfolgreich zu sein. 

Welche Kriterien gelten bei der Nominierungen von https://innersourcecommons.org/resources/learningpath/contributor/index[Contributors] für die Rolle des _Trusted Committers_? Was benötigt man, um die Rolle des _Trusted Committers_ erfolgreich auszufüllen? Zuallererst müssen potentielle _Trusted Committer_ ihre tiefe technische Kompetenz während ihrer Arbeit in der Community unter Beweis stellen. Zusätzlich dazu müssen sie zeigen, dass sie wirkungsvoll mit den Kollegen der Community, und idealerweise genauso mit den Product Ownern und dem Management, zusammen arbeiten können.

Auf dieselbe Art müssen sie den Willen und die Geduld aufweisen, ihre Fähigkeiten zu nutzen und bewusst sich Zeit nehmen, um _Contributors_ weiter zu qualifizieren. Schließlich erfordert die Erfüllung der Rolle des _Trusted Committers_ eine gewisse emotionale Reife, um mit stressvollen sozialen Situationen umzugehen die mit Sicherheit ab und zu aufkommen.
Contributors, welche diese Kriterien erfüllen, sind nach unserer Meinung gute Kandidaten für potentielle _Trusted Committers_.

Die Rolle des _Trusted Committers_ wird nicht für alle Contributors attraktiv sein, bedeutet es doch, dass man weniger Zeit verbringt, selbst zu programmieren. Als _Trusted Committer_ vorgeschlagen zu werden kann sogar herabstufend empfunden oder als negatives Feedback bezüglich der eigenen Programmierfähgigkeiten aufgefasst werden. Aber das Gegenteil ist der Fall. Als _Trusted Committer_ nominiert zu werden, bedeutet normalerweise, dass man deine wertvollen Beiträge erkannt hat und in dir das Potential weiter zu wachsen und zu führen sieht. Die Rolle des _Trusted Committers_ gib dir mehr Einfluß auf die Entwicklung der Codebasis und macht dich definitiv zu einem vollständigeren Entwickler. Contributors zu erklären, wie die Software funktioniert, die Rolle führt häufig zu neuen Erkenntnissen seitens des _Trusted Committers_, und hilft Möglichkeiten zu identifizieren die Software weiter zu verbessern.

Ob es einer InnerSource Community einen oder mehrere _Trusted Committer_ gibt, hängt von der Größe und dem Risiko ab, welches mit ihrer Software verbunden ist.
Die Rolle des _Trusted Committers_ ist zeitaufwändig, und nicht jeder ist gewillt oder hat die Möglichkeit diese Verpflichtung einzugehen. Aus diesem Grund nutzen mache Unternehmen ein Rotationssystem, in dem sich mehrere _Trusted Committer_ die Arbeitslast teilen, und diejenigen _Trusted Committer_, die gerade nicht an der Reihe sind, können sich ausschließlich technischen Themen widmen. Mehr als einen _Trusted Committer_ zu haben macht es auch leichter, wenn jemand das Unternehmen verlässt oder wenn jemand sich aus der Rolle in eine neue Aufgabe verändert. Für diesen Fall ist es wichtig, dass schon andere _Trusted Committer_ bereit stehen, die die Aufgaben übernehmen können um Kontinuität in der Gemeinschaft sicherzustellen.

Zusammengefasst erwirbt man sich die Rolle des _Trusted Committer_ durch Erstellen von wertigen Beiträgen zum Wohl der Community - sowohl technisch als auch sozial. In einer gut aufgestellten Community hast du andere _Trusted Committer_ an deiner Seite. Als _Trusted Committer_ wirst du weniger Zeit verbringen selbst zu programmieren, aber wenn du als Multiplikator agierst, wirst du letztendlich deinen Wertbeitrag verstärken und dein eigenes Wachstum beschleunigen.

