== Conclusión

Thanks for reviewing the Contributor segment of the InnerSource Commons Learning Path. With this section you've learned about the Contributor role - the life blood of InnerSource projects.  Contributors are external to the component owners' team, and they bring additional valuable input to the project.

In this section you've learned about how to become a contributor by finding opportunities to contribute. 
We have reviewed the mindset and habits needed to find or create such opportunities.
We've also discussed the ethos of the role and a suggested approach that is likely to lead to successful contributions.

Given the right mindset, habits and ethos, there are still a few details that might keep you from successfully contributing - hence, we've discussed these nuts and bolts in greater detail.

Last but not least, convincing your teammates and your organization at various levels can be hard, thus we've discussed the benefits of contribution from various perspectives to make this process easier for you.

We hope you've enjoyed watching the videos, and/or and reading the articles, and will be able to take away some interesting new insights for your journey towards InnerSource and being a good contributor.

If you haven't done so already, we would like to invite you to learn more about the other aspects of InnerSource in our InnerSource learning path: http://innersourcecommons.org/learningpath/

We invite you to check out the InnerSource group http://innersourcecommons.org[InnerSource Commons] online - feel free to join the discussion and share your experiences and lessons learnt in your organization.

Live long and have prosperous projects!


== Conclusión

Gracias por revisar el segmento Colaborador de la ruta de aprendizaje de InnerSource Commons. En esta sección, ha aprendido sobre el rol de contribuidor, la sangre vital de los proyectos de InnerSource. Los colaboradores son externos al equipo de propietarios de componentes y aportan información adicional valiosa al proyecto.

En esta sección, ha aprendido cómo convertirse en colaborador al encontrar oportunidades para contribuir.
Hemos revisado la mentalidad y los hábitos necesarios para encontrar o crear tales oportunidades.
También discutimos el espíritu del rol y un enfoque sugerido que probablemente conduzca a contribuciones exitosas.

Dada la mentalidad, los hábitos y la ética correctos, todavía hay algunos detalles que podrían evitar que contribuya con éxito; por lo tanto, hemos discutido estos aspectos básicos con mayor detalle.

Por último, pero no menos importante, convencer a sus compañeros de equipo y a su organización en varios niveles puede ser difícil, por lo que hemos discutido los beneficios de la contribución desde varias perspectivas para facilitarle este proceso.

Esperamos que haya disfrutado viendo los videos y / o leyendo los artículos, y podrá obtener algunas ideas nuevas e interesantes para su viaje hacia InnerSource y ser un buen colaborador.

Si aún no lo ha hecho, nos gustaría invitarlo a aprender más sobre los otros aspectos de InnerSource en nuestra ruta de aprendizaje de InnerSource: http://innersourcecommons.org/learningpath/

Lo invitamos a visitar el grupo de InnerSource http://innersourcecommons.org [InnerSource Commons] en línea; no dude en unirse a la discusión y compartir sus experiencias y lecciones aprendidas en su organización.

¡Viva mucho y tenga proyectos prósperos!