# Transcripción: El contribuidor en InnerSource – Introducción 

=== Duración: 1-3 Minutos

=== Actores: Isabel y Johannes

=== Resumen del “PlayBook”

Este segmento recapitula que hemos aprendido acerca de ser un contribuidor InnerSource. Compartiremos como puedes continuar tu aprendizaje sobre InnerSource en línea, tanto con otros videos como involucrandote en la comunidad de InnerSource.

=== Guión

J: Gracias por ver el segmento de Contribuidor de la ruta de aprendizaje de InnerSource Commons. Con esta sección aprendiste sobre el rol de contribuidor – La sangre vital de los proyectos de InnerSource:
Ajeno al equipo de los propietarios de un componente, éste aportan valor adicional al proyecto.

I: Has aprendido a cómo convertirte en un Contribuidor, buscando oportunidades para contribuir, así como la mentalidad y los hábitos necesarios para encontrar o crear tales oportunidades.
También discutimos la ética del rol y sugerimos algún comportamiento que probablemente le conduzca a contribuciones exitosas.

J: Dada la mentalidad correcta, los hábitos y la ética aún hay algunos detalles que podrían evitar que contribuya con éxito; por lo tanto, hemos discutido estos aspectos básicos con mayor detalle.

I: Por último, pero no menos importante, convencer a tus compañeros de equipo y a su organización a varios niveles puede ser difícil, por lo que hemos discutido los beneficios de la contribución desde varias perspectivas para facilitarte el proceso.
J: Esperamos que haya disfrutado viendo los videos y leyendo los artículos. Esperamos que pueda obtener algunas ideas nuevas e interesantes para su viaje hacia InnerSource y ser un buen Contribuidor.

I: Si aún no lo has hecho, nos gustaría invitarte a aprender más sobre los otros aspectos de InnerSource en nuestra ruta de aprendizaje de InnerSource:
http://innersourcecommons.org/learningpath/

\-> Capa para mostrar link

¡Se bienvenido a visitar adicionalmente el grupo de InnerSource 
http://innersourcecommons.org [InnerSource Commons] en línea!
Siéntete libre de unirte al debate y compartir tus experiencias y lecciones aprendidas.

\-> Capa para mostrar link. innersourcecomms.org/invite ¿Capa especial personalizable que podríamos mapear al invitador de Slack o algún otro lado o podríamos dejar el dominio en blanco?

J: Larga vida y que tengas proyectos prósperos.