== Trusted Committerになる

Trusted Committerの役割は、大変ですがやり甲斐のあるものです。
このラーニングパスに興味があるのであれば、実際にTrsuted Committerになる方法と、自分がそれに適した人物であるかを知りたいと思うかもしれません。

InnerSourceコミュニティは、オープンソースコミュニティと同じ原則に従っており、その一つに実力主義があります。
実力主義において、権力は才能、努力、成果に基づいて個人に与えられます。
つまり、Trusted Committerの役割に伴う権限と特権は、獲得する必要があるものだということです。
オープンソースのもう1つの価値である透明性は、才能、努力、成果をコミュニティ全体に見えるようにするという点でも重要な役割を果たしています。

正式にTrusted Committerになるプロセスは、コミュニティごとに異なり、InnerSourceの行路のどこにいるかに依り、時間とともに進化するかもしれません。
草の根コミュニティでは、創設者がTrusted Committerの役割を担うことが良くあります。
コミュニティが成長するにつれて、またはより大きなコミュニティでは、Trusted Committerは通常、コミュニティの https://innersourcecommons.org/ja/learn/learning-path/contributor[コントリビューター] から指名されたり投票されたりします。
しかし、Trusted Committerの役割は、成功のために多大な時間と献身を必要とするため、自発的に引き受けなければなりません。

https://innersourcecommons.org/ja/learn/learning-path/contributor[コントリビューター] をTrusted Committerの役割に指名する際に適用する基準は何ですか？
Trusted Committerの役割をうまく果たすには何が必要ですか？
まず、Trusted Committerの候補は、コミュニティでの活動で、高度な技術力をを示す必要があります。
それに加えて、コミュニティの仲間や、理想的にはプロダクトオーナーや経営陣とも効果的にコミュニケーションできることを証明していなければなりません。

同様に、自分たちのスキルを活用し、コントリビューターのレベル向上に意図的に時間を割く意欲と忍耐力を示さなければなりません。
最後に、Trusted Committerの役割を果たすには、時に起こるストレスの多い社会的状況に対処するために、ある程度の感情的な成熟が必要となります。
これらの基準を満たしているコントリビューターは、Trusted Committerになる可能性があると私達は考えています。

Trusted Committerの役割は、コーディングに費やす時間が少ないため、一部のコントリビューターには魅力的に見えないかもしれません。
Trusted Committerの役割に指名されたということは、降格やコーディングスキルに対する否定的なフィードバックと受け取られることさえあるかもしれません。
しかし、その逆も真です。
Trusted Committerの役割に指名されるということは、通常、誰かがあなたの貴重なコントリビューションを認め、あなたの成長とリードに可能性を見出しているということになります。
Trusted Committerの役割は、コードベースの進化に対してより大きな影響力をあなたに与え、最終的により成熟した開発者にするでしょう。
コントリビューターに対してソフトウェアがどのように動作するか説明することは、たいていの場合、一部のTrusted Committerに対して新しい見識をもたらし、ソフトウェア改善機会の見極めに役立つことになるでしょう。

Trusted Committerを一人または複数持つかは、InnerSourceコミュニティによって開発されるソフトウェアのサイズとリスクに依存します。
Trusted Committerの役割は、時間がかかるもので、誰もがその種の約束をできたり、進んでしたりする訳ではありません。
このため、一部の企業では _Trusted Committerの当番制_ を用いて、複数のTrusted Committerがその役割の作業量を共有し、 _当番_ でないTrusted Committerが技術的な作業に専念できるようにしています。
複数のTrusted Committerがいると、誰かが会社を辞めたり、現在の役割から別のことをする事になる場合にも楽になります。
その場合には、引き継いでコミュニティの継続性を確保できる他のTrusted Committerが既にいることが重要です。

まとめると、Trusted Committerの役割は、コミュニティの利益のために、技術的にも社会的にも価値があるコントリビューションをすることによって獲得されなければなりません。
健全なコミュニティでは、Trusted Committerの仲間があなたの味方になります。
Trusted Committerとしてコードを書く時間は短くなりますが、フォースマルチプライヤーとして行動することで、最終的にはコミュニティへのコントリビューションの価値を高め、自身の成長を加速することができます。
