[[advocating]]

== Abogar por las necesidades de la comunidad

Las comunidades InnerSource existen en un contexto corporativo, por ende están más apretadas que las comunidades Open Source.
A veces los interes de la unidad de negocio están en desacuerdo con los de la comunidad.
Los Trusted Committers toman una perspectiva a largo plazo de su proyecto.
Ellos entienden que un comunidad sana es una precondición para un código sano.
Es por esto que muchas iniciativas de InnerSource están modeladas a la manera Apache, su lema es http://theapacheway.com/community-over-code/["Comunidad sobre código"].
Las Unidades de la empresa, por otro lado, están naturalmente más preocupadas por los productos producidos por una comunidad InnerSource.
Ellos prefieren ver resultados a corto o medio plazo que ayudan a la cuenta de resultados.

Es en esta área de conflicto potencial donde los Trusted Committers juegan un rol vital.
Los Trusted Committers construyen confianza con la organización y,
construyendo en esa confianza,
actúan como abogados por los interes de la comunidad y la salud a largo plazo del software en la compañia.
Ellos son responsables de comunicar riesgos técnicos y de la comunidad a jefatura.
Al mismo tiempo los Trusted Committers necesitan ser estratégicos y trabajar dentro de los grados de libertad concedidos por la compañia.

Los Trusted Committers también deben asegurarse que la comunidad y los https://innersourcecommons.org/learn/learning-path/contributor[Contribuidores] individuales reciban el reconocimiento público de su trabajo.
El reconocimiento público es la moneda con la que se les paga a los contribuidores, especialmente aquellos que contribuyen de manera voluntaria.
Es una buena práctica el elogiar públicamente contribuidores valiosos y que sus gerentes sepan de sus contribuciones.
Descuidar el dar reconocimiento puede ser frustante para los contribuidores individuales y pueden ser perjudicial para la salud de la comunidad.
Esto puede ocurrir en compañias que aun no se adaptan al modelo de trabajo InnerSource,
o cuando un software que está siendo desarrollado por la comunidad InnerSource se ejecuta _en segundo plano_ y los gerentes simplemente no son conscientes de las contribuciones de la comunidad.
Un buen Trusted Committer está comprometido con la jefatura y abogará por el reconocimiento público.
El fallar al otorgar reconocimiento no suele ser por mala fé y es fácil de arreglar.

Otro caso común para llamar a los Trusted Committers a abogar es cuando los https://innersourcecommons.org/learn/learning-path/contributor[contribuidores] no se les da el tiempo o permiso de contribuir.
Esto pueden pasar cuando una comunidad está trabajando en un producto fuera del departamento del contribuidor
y por ende no es relevante para las metas del gerente.
En este caso, el Trusted Committer debe comprometerse en la discución con el gerente del contribuidor y abogar por una decisión alternativa.

En resumen, Hay muchas situaciones donde los Trusted Committers necesitan abogar por los intereses de https://innersourcecommons.org/learn/learning-path/contributor[contribuidores] individuales y por la comunidad en general.
Los Trusted Committers entienden que el valor que una comunidad puede proporcionar a la empresa depende de la salud y longevidad de esta y fundamentalmente en un relación de confianza entre ambas.