== Quais são os benefícios do InnerSource?

Há muitos benefícios em colaborar via InnerSource.
O InnerSource oferece à empresa uma estratégia escalável para *equipes convidadas obterem solicitações de recursos quando precisarem* sem o ônus de manutenção de longo prazo.
A empresa como um todo ganha à medida que o tempo das equipes convidadas é colocado em código que outras pessoas podem usar.

Embora esse resultado seja um benefício brilhante do InnerSource, há muitos benefícios para as equipes anfitriãs que recebem contribuições regulares do InnerSource.
Lembre-se de que, como parte do processo InnerSource, o Product Owner na equipe anfitriã concorda desde o início que os recursos fornecidos são bons e desejáveis.
A InnerSource permite que a equipe anfitriã receba *ajuda na criação de um produto melhor* para seus consumidores!

*InnerSource fornece à equipe anfitriã uma estratégia escalável* para atender a quantidades variadas de recursos solicitados por seus muitos consumidores.
Dada a capacidade fixa dos membros em tempo integral da equipe anfitriã, é provável que, às vezes, os roteiros de negócios combinados de seus consumidores exijam quantidades muito (ou mesmo irracionais) de trabalho a serem feitas nos produtos da equipe anfitriã.
Sem o InnerSource, essa situação leva facilmente a uma equipe estressada e sobrecarregada lidando com muitas solicitações de recursos encaminhadas a seus líderes.

No entanto, se a equipe anfitriã operar via InnerSource, os recursos de engenharia necessários para construir esses recursos aparecerão proporcionalmente à sua importância na forma de contribuidores convidados.
*InnerSource torna-se um multiplicador de força* que permite que a equipe anfitriã aja temporariamente maior do que seu tamanho real durante períodos de alta demanda.
Quando a demanda termina, o rendimento da equipe volta aos níveis normais, tudo sem qualquer microgerenciamento do número de funcionários ou itens de trabalho da equipe.
O InnerSource permite que o tempo de engenharia flua organicamente onde a organização precisa dele em um determinado momento.

Além do trabalho bruto que a equipe anfitriã é capaz de realizar em seu sistema, as contribuições regulares do InnerSource fornecem à equipe anfitriã *melhores requisitos e alinhamento de priorização com todos os seus consumidores*.
Uma equipe anfitriã pode fazer o melhor levantamento de requisitos sobre o trabalho que produz, mas quando o próprio consumidor é quem está enviando o trabalho, as chances são muito maiores de que a mudança resultante esteja alinhada exatamente com o que o consumidor precisa.
Embora possa ser apenas uma única equipe convidada enviando a alteração, essa equipe provavelmente representa muitos outros consumidores.

Além desse alinhamento, há também um treinamento geral e educação de https://innersourcecommons.org/learn/learning-path/contributor[contribuidores] enquanto eles trabalham e aprendem com https://innersourcecommons.org/learn/ Learning-path/trusted-committer[trusted committers].
Essa interação ajuda os colaboradores a aprender e crescer em suas carreiras, resultando em *maior satisfação no trabalho*.
A documentação do projeto melhora para permitir essas contribuições em escala.
Os contribuidores sentem uma participação no projeto da equipe anfitriã.
É algo que eles recomendam a seus colegas ou novas equipes que eles ingressam.
Eles entendem melhor o projeto e são capazes de responder a perguntas sobre ele para outras pessoas, aliviando a equipe de acolhimento de um pouco desse fardo.
Mais pessoas contribuindo para um projeto naturalmente polinizam ideias de toda a empresa.
Esse aprendizado e alinhamento entre equipes ao longo do tempo serve para *quebrar os silos tradicionais da empresa*.