:doctype: book

O objetivo deste documento é manter o material complementar e de planejamento relacionado ao conteúdo dos segmentos introdutórios desta Trilha de Aprendizado.

== Objetivos

Esses segmentos da trilha de aprendizado são os primeiros de uma série que apresenta o InnerSource.
Esta trilha de aprendizado deve ser o ponto focal e o contexto compartilhado da conversa pública atual sobre o InnerSource.
Para atingir esse objetivo, esta introdução deve fornecer:

* Definições convincentes e claras em torno de 5 termos-chave:
  ** Anfitrião (equipe)
  ** Convidado (equipe)
  ** Trusted Committer
  ** Product Owner
  ** Contributor/Contribuidor
* Guardrails para os atributos mínimos viáveis do InnerSource:
  ** Contribuição voluntária do código
  ** Mentoria Priorizada
* Interesse e expectativa dos espectadores em assistir aos segmentos restantes do caminho de aprendizado

== Público

O público deste caminho de aprendizado é qualquer pessoa que já ouviu falar do InnerSource.

== Contorno

=== Introdução

Apresente o tópico, por que é importante e o que o espectador aprenderá nesta Trilha de Aprendizado.

=== Justificativa

Compartilhe uma situação de exemplo hipotética (ainda crível) que ilustre as dificuldades atuais no processo de colaboração entre os silos organizacionais.
Essa situação específica será a base à qual nos referimos ao longo do caminho de aprendizado, principalmente ao apresentar os 5 termos-chave e evitar equívocos sobre o InnerSource.

=== Solução

Mostre como os jogadores na situação de exemplo podem colaborar via InnerSource para superar suas dificuldades.
Explique os benefícios dessa abordagem.
Ao dar esta explicação, inclua naturalmente definições claras dos 5 termos-chave e também palavras especificamente projetadas para dissipar equívocos sobre o InnerSource.

=== Explicação adicional

Aprofunde-se em algumas "`pegadinhas`" e pontos mais sutis sobre o processo InnerSource.
Considere o uso estratégico de piadas curtas e convincentes para consolidar ainda mais as partes principais da mensagem.
Tendência para incluir material nesta seção que dissipa ainda mais os equívocos do InnerSource e também prepara o terreno para os próximos segmentos na Trilha de Aprendizado.

=== Conclusão

Revise os pontos-chave desta trilha de aprendizado e prepare os espectadores para procurar os próximos segmentos.
Convide os espectadores interessados a participar do InnerSource Commons.