= Introducing the Trusted Committer role

The Trusted Committer (TC) role is one of the key roles in an InnerSource
community. Think of Trusted Committers as the people in a community that you trust with
important technical decisions and with mentoring contributors in order to get
their contribution over the finish line. The Trusted Committer role is both a demanding and a
rewarding role to fulfill. It goes far beyond being an opinionated gatekeeper
and it is instrumental for the success of any InnerSource community.

Generally speaking, the Trusted Committer role is defined by its responsibilities, rather than
by its privileges. On a very high level, Trusted Committers represent the interests of both
their InnerSource community and the products the community is building. They
are concerned with the health of both the community and the product. So as a
Trusted Committer, you'll have both tech oriented and community oriented responsibilities.  We'll
explore both of these dimensions in the following sections.

Before we go into the details of what a Trusted Committer actually does, let's spend some time
contrasting the Trusted Committer role to other roles in InnerSource on a high level of abstraction and
explain why we think the name is both apt and important.  Let's
start with the https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributor_] role. A _Contributor_ - as the name implies -
makes contributions to an InnerSource community.  These contributions could be code or non-code
artifacts, such as bug reports, feature requests or documentation.
_Contributors_ might or might not be part of the community. They might be sent by
another team to develop a feature that their team needs. This is why we
sometimes also refer to _Contributors_ as _Guests_ or being part of a _Guest
Team_. The _Contributor_ is responsible for "fitting in" and for conforming to the
community's expectations and processes.

The _Trusted Committer_ is always a member of the InnerSource community, which is
also sometimes referred to as the _Host Team_. In this analogy, the Trusted Committer is
responsible for both building the house and setting the house rules, to make
sure their guests are comfortable and can work together effectively. Compared
to contributors, Trusted Committers have earned the responsibility to push code closer to
production, and are generally allowed to perform tasks that have a higher level
of risk associated with them.

The https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/01-opening-article.md[_Product Owner_ (PO)] is the third role in InnerSource.  Similar to agile
processes, the PO is responsible for defining and prioritizing requirements and
stories for the community to implement. The PO interacts often with the
Trusted Committer, e.g. in making sure that a requested or contributed feature actually
belongs to the product. Especially in smaller, grass-roots type InnerSource
communities, the Trusted Committer usually also acts as a PO. Please check out our https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/product-owner/01-opening-article.md[Product
Owner Learning Path segment] for more detailed information.

== Why role names matter

The role of the Trusted Committer is present in every successful InnerSource community, but not
every community uses that name. Some communities use the term Maintainer, but
it turns out that it conflicts with the technical role "Maintainer" defined by
GitHub, for instance.  Apache uses the term _Committer_, too, but they attach
fewer and mostly tech oriented responsibilities to that role. The Trusted Committer role with
its additional community oriented responsibilities goes beyond that.  The
"Trusted" in Trusted Committer conveys that they are trusted and thus empowered by both their
management and their community to do their job. By fostering openness and
transparency, Trusted Committers build trust in the process and also in the product being
built.

So similar to how naming is important in writing software, it is important for the
roles in an InnerSource project as well. Choosing the right names and doing so
consistently ensures that everyone has the same notion of the role and how it
serves the community.

Now you should have a basic understanding of the role, why using the term
_Trusted Committer_ is appropriate, and understand how a Trusted Committer might
interact with other common roles in a software project.

== Responsibilities

In the following segments, we'll dive into the various responsibilities that
Trusted Committers have:

* https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/02-ensuring-product-quality.md[ensuring product quality],
* https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/03-keeping-the-community-healthy.md[keeping the community healthy],
* https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/05-lowering-the-barriers-to-entry.md[reducing the barrier to making contributions],
* https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/04-uplevelling-community-members.md[upleveling the community],
* https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/06-advocating-for-the-communitys-needs.md[advocating the communities needs].

In addition, we will also explore the path of https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/07-becoming-a-trusted-committer.md[becoming a Trusted Committer] in the end
of this article.
