= Uplevelling community members

Let's talk about participation. There is a continuum of participation in an
InnerSource community. There are people not even aware of the community,
_newcomers_ which are aware of the community but have not yet used or contributed
to the software, _consumers_ which already use the software, https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributors_] who
have made at least one contribution and _Trusted Committers_, who take responsibility for both
the software and the community. As a Trusted Committer, you are responsible for moving
individuals along this continuum and to uplevel their ability to make
contributions. In that sense, Trusted Committers act as force multipliers in their community.

As indicated earlier, it is helpful for Trusted Committers to engage in marketing their
product and their community in order to increase the number of newcomers and
consumers. They should communicate opportunities for making contributions to
consumers and try to elicit and align the interests of potential https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributors_]
with those of the community. What often works well is if Contributors were able
to work on something that made their day job easier, e.g. development tools and automation.

Finally, it is the Trusted Committer's responsibility to identify https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributors_] with the
potential to grow.  They should foster and nurture that growth by getting
Contributors excited for tackling challenging tasks and to mentor or coach them
while they are performing them. This is, in our opinion, the noblest
responsibility a Trusted Committer has. It is rewarding for both the Contributor and the
Trusted Committer alike. We have heard from Trusted Committers that mentoring and seeing people level up
their abilities more than makes up for the fact that they have less time to
actually spend writing software.

As mentioned in the https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/trusted-committer/03-keeping-the-community-healthy.md[previous section], learning and personal growth are reasons
why people join and stick around in an InnerSource community. Upleveling their
https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributors_] is one of the most powerful tools Trusted Committers have at their disposal to
increase the speed, output and longevity of their community. It is also one of
the key arguments with which to convince management to allow their employees to
participate in an InnerSource community, as that will make their employees more
valuable to them, to the company overall and it will help retain top talent.

In summary, Trusted Committers need to attract new https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/master/contributor/01-introduction-article.md[_Contributors_] and level up their ability to
make contributions.  This activity ultimately levels up the community's ability to create
better software faster. They do so by communicating opportunities to make
contributions and by helping and mentoring Contributors to grow
