
[[upleveling]]
== Upleveling Community Members

There is a continuum of participation in
an InnerSource community. Newcomers might be interested in the community and its product, but have not yet used it. Consumers use the software but may not have made a contribution. Then there are the contributors, and finally the TC, who is taking responsibility for both the software and the community.
As a TC, you are responsible for moving individuals along this continuum
and upleveling their ability to make contributions. In this sense, TCs
act as force multipliers in their community.

It is important for TCs to market their
product and communities to increase the number of
newcomers and consumers. They should also communicate opportunities to
make contributions to consumers and try to elicit and align the
interests of potential contributors with that of the community. What
often works well is if contributors are able to work on something that
benefits their department or role in the company. Development tools and automation are good examples.

Finally, it is the TC's responsibility to identify and support contributors with the
potential to grow by encouraging them to tackle challenging tasks and helping them complete them. This is, in my opinion, a TC's
noblest responsibility, and it is rewarding for both TC and
contributor. We've heard TCs say that mentoring and
seeing people level up their abilities more than makes up for the fact
that they have less time to actually spend writing software.

As mentioned in the previous section, learning and personal growth are
reasons people join and stick around in an InnerSource community.
Upleveling their contributors is one of the most powerful tools TCs have
at their disposal to increase the speed, output, and longevity of their
communities. It is also one of the key arguments with which to convince
management to allow their employees to participate in an InnerSource
community, as that will make their employees more valuable to 
the company overall and help them retain top talent.

In summary, TCs need to attract new contributors and level up their
ability to make contributions. This activity ultimately levels up the
community’s ability to create better software faster. They do so by
communicating opportunities to make contributions and by helping and
mentoring contributors.
