
[[advocating]]
== Advocating for the Community’s Needs

InnerSource communities exist in a corporate context and are thus more constrained than Open Source communities. Sometimes the
business unit’s interests are at odds with those of the community.
TCs take a long term perspective on their project. 
They understand that a healthy community is a precondition for healthy code. 
This is why many InnerSource initiatives were modeled in the Apache Way: http://theapacheway.com/community-over-code/["Community over Code"]. 
Business units, on the other hand, are naturally more concerned with the bottom line and thus with short-term software release goals.

It is in this potential area of conflict where the TC plays a vital role. 
TCs build trust with the organization and, building on that trust, act as an advocate for the interests of the community and the long term health of the software in the company. 
They are responsible for communicating technical- as well community-related risks to management.
At the same time, TCs need to be strategic and work within the degrees of freedom afforded by their companies.

TCs also need to make sure that the community and individual
contributors get public credit for their work. Public credit is the
currency with which contributors are being paid, especially those who
contribute voluntarily. It is good practice to commend valuable
contributors publicly and to make sure their managers are aware of their contributions.
Neglecting to give credit can be detrimental to the health of the
community. This can happen in companies not yet accustomed to the InnerSource working model or when
the software being developed by the InnerSource community runs _behind
the scenes_ and managers were simply not aware of the community’s
contribution. A good TC will engage with management and advocate for public credit. Failure to give credit is almost
never done in bad faith and is usually easy to fix.

Another key responsibility of TCs is making sure contributors are given the time they need to make contributions. 
Getting time to contribute can be challenging, especially when the contribution is made to a project not relevant to the contributor's department. In this case, the
TC should engage in discussion with the contributor’s manager and lobby
for an alternative decision.

In summary, there are many situations in which TCs need to advocate for the
interests of individual contributors and for the community as a whole. TCs understand that the value the community can provide to the organization depends on the health
and longevity of the community and ultimately on a trustworthy
relationship between both.
