
[[advocating]]
== Advocating for the Community’s Needs

InnerSource communities exist in a corporate context and are thus more constrained than Open Source communities. Sometimes the
business unit’s interests are at odds with those of the community.
Trusted Committers take a long term perspective on their project. 
They understand that a healthy community is a precondition for healthy code. 
This is why many InnerSource initiatives were modeled in the Apache Way with its http://theapacheway.com/community-over-code/["Community over Code"] motto. 
Business units, on the other hand, are naturally more concerned with the products produced by an InnerSource community. 
They prefer to see short to medium-term results that help the bottom line.

It is in this potential area of conflict where the Trusted Committer plays a vital role. 
Trusted Committers build trust with the organization and, building on that trust, act as advocates for the interests of the community and the long term health of the software in the company. 
They are responsible for communicating technical, as well as community-related, risks to management.
At the same time, Trusted Committers need to be strategic and work within the degrees of freedom afforded by their companies.

Trusted Committers also need to make sure that the community and individual https://innersourcecommons.org/learn/learning-path/contributor[contributors] get public credit for their work. 
Public credit is the currency with which contributors are being paid, especially those who contribute voluntarily. 
It is a good practice to commend valuable contributors publicly and to make sure their managers are aware of their contributions.
Neglecting to give credit can be frustrating for individual contributors and detrimental to the health of the community. 
This can happen in companies not yet accustomed to the InnerSource working model, or when the software being developed by the InnerSource community runs _behind the scenes_ and managers were simply not aware of the community’s contribution. 
A good Trusted Committer will engage with management and advocate for public credit. 
Failure to give credit is almost never done in bad faith and is easy to fix.

Another common case calling for the Trusted Committer’s advocacy is when  https://innersourcecommons.org/learn/learning-path/contributor[contributors] are not given time or permission to contribute. 
This can happen when the community is working on a product outside of the contributor's department and thus not relevant for their manager’s goals. 
In this case, the Trusted Committer should engage in discussion with the contributor’s manager and lobby for an alternative decision.

In summary, there are many situations in which Trusted Committers need to advocate for the interests of individual https://innersourcecommons.org/learn/learning-path/contributor[contributors] and for the community as a whole. 
Trusted Committers understand that the value the community can provide to the organization depends on the health and longevity of the community and ultimately on a trustworthy relationship between both.

