= Conclusion

In the past sections, we have learned about the responsibilities of Trusted Committers;
ensuring product quality, keeping their community healthy, reducing the barrier
to making contributions, upleveling the community and advocating the
community's needs in their organization. We also talked about how to become a
Trusted Committer and what it takes to fill that role. Working as a Trusted Committer will be demanding but
it will also be very fulfilling and will help you amplify your value contribution
in your company.

In that sense, we hope that this section inspired you to set off on a path
towards becoming a Trusted Committer.  We also hope that this section helped your organization understand the
importance of having capable Trusted Committers for the success of any InnerSource initiative
and the level of empowerment that this role requires.

We'd like to invite you to learn more about InnerSource by exploring the other
articles and videos in the InnerSource Learning Path. And of course, we'd be
thrilled to welcome you in http://www.innersourcecommons.org/[the InnerSource commons community].

May the source be with you.
