== Conclusion

In the previous chapters, we've learned about the responsibilities of a TC.
Some of these responsibilities include ensuring product quality, keeping their community healthy, reducing the
barriers to making contributions, upleveling the community and advocating
for its needs within the organization. We also talked about how to
become a TC and what it takes to fulfill that role. Working as a TC is
demanding but will ultimately amplify
your value contribution in your company.

We hope we've inspired you to set off on a
path towards becoming a TC. We also hope we've helped your
organization understand the importance of having capable TCs for the
success of any InnerSource initiative and the level of empowerment that
this role requires.

We’d like to invite you to learn more about InnerSource by exploring the
other articles and videos in the InnerSource Learning Path. And of
course, we’d be thrilled to welcome you in
http://www.innersourcecommons.org/[the InnerSource Commons community].

May the source be with you.
