== Выводы

В этом обучении мы получили вводную информацию по InnerSource.
InnerSource применяет лучшие практики и принципы из мира open source к внутренней разработке.
Подход даёт возможность командам получить необходимый функционал в соседних командах, неспособных выполнить запрос на доработку.
Успешный InnerSource включает в себя работу https://innersourcecommons.org/resources/learningpath/product-owner/index[_Владельца продукта_] и https://innersourcecommons.org/resources/learningpath/trusted-committer/index[_Trusted Committer_] из *хост-команды* и https://innersourcecommons.org/resources/learningpath/contributor/index[_Контрибьютера_] из *гостевой команды*.

При эффективном использовании InnerSource даёт преимущества обеим командам.
*Приоритетное менторство* и *Добровольная Контрибьюция Кода* – принципы, влияющие на эффективность InnerSource.

Это обучение содержит только общую информацию по InnerSource и существует множество деталей полезных для того, чтобы InnerSource действительно работал на вашу команду.
Присоединяйтесь к http://innersourcecommons.org[the InnerSource Commons] для обмена лучшими практиками InnerSource.
Сообщество использует Slack для общения и обмена опытом, поддерживает работу различных рабочих групп, таких как паттерны InnerSource, а также проводит профильные конференции несколько раз в год.
Участие в сообществе это отличный способ оставаться на связи и получать последние новости на тему InnerSource.