== はじめに

=== InnerSourceのコントリビューター

あなたは、あなたの依存する機能を他チームがシステムに追加をする時間が無いために、次のコーディングタスクをブロックされたことはありませんか？
もしかすると、しばらくしてから、その不足している機能を補うために、あなたのプロジェクトで余計な作業をしなければならなかったかも知れません。
このような形で全くブロックされないことは、どんなに素晴らしいことでしょうか？

InnerSourceの原則を組み込んだプロジェクトでは、必要な機能を他のチームが提供するのを待ってブロックされることは決してありません。
もし必要なものが得られないなら、InnerSourceコントリビューターとして行動し、他チームのコードリポジトリに直接あなたが必要な変更を行うことかできます。

コントリビューターの役割は、InnerSourceコミュニティプロジェクトのリポジトリに貢献する人と表されます。
この人はコミュニティの一部の人であるかも知れないし、そうでないかも知れません。
しかし、かなりの数の人にとってコントリビューターとは、単にコミュニティについて知るだけのことから、コミュニティのプロダクトを使用し、コミュニティのメンバーと対話し、そして最終的に貢献を始めることができるという旅のようなものです。
最終的に、そのうち何人かは https://innersourcecommons.org/learn/learning-path/trusted-committer[Trusted Committer (トラステッドコミッター)] になるかも知れません。

=== 他の役割との関係

InnerSourceコミュニティにおけるコントリビューターとしてあなたは、 https://innersourcecommons.org/learn/learning-path/trusted-committer[_トラステッドコミッター_] や https://innersourcecommons.org/learn/learning-path/product-owner[_Product Owner (プロダクトオーナー)_] などのInnerSourceの他の役割を担っている人や、おそらく他のコントリビューターとも交流することになります。
まれに、小さな草の根スタイルのプロジェクトでは、トラステッドコミッターとプロダクトオーナーなどの役割は同じ人が行うことができます。

この節では、他の2つの役割について非常に短い概要を説明しますが、 https://innersourcecommons.org/learn/learning-path/trusted-committer[トラステッドコミッターの役割の紹介記事] と https://innersourcecommons.org/learn/learning-path/trusted-committer/05/[参加障壁を下げる] 記事を、コントリビューターの役割をより深く掘り下げて説明する前に読むことを推奨します。
記事を読む代わりに、ビデオ (https://innersourcecommons.org/learn/learning-path/trusted-committer[入門]、 https://innersourcecommons.org/learn/learning-path/trusted-committer/05/[参入障壁を下げる]) を見ることもできます。

==== トラステッドコミッター

トラステッドコミッターは、ホスティングするコミュニティにあなたが滞在する間、あなたのホストになります。
彼らはプロジェクトのコードリポジトリのゲートキーパーで、あなたの貢献を彼らが受け入れた時、それをプロダクションレベルに近づけてくれます。
彼らの役割は、あなたが彼らのコミュニティに貢献するための指導をすることです。
彼らは、あなたを直接助けたり、あなた自身で解決できるようにするための情報を提供したりします。
この情報は、レビューのためのハウスルール、大きな変更の提案テンプレート、あなたの貢献に関するコードセクションやドキュメントへのポインタなどで構成されます。

彼らはまた、プロダクトの品質、持続可能性とプロジェクトの進化など技術的な側面とともに、一般的な側面となる、すべての人に貢献することへの障壁を減らすことやコミュニティ全般のケアもする必要があります。
コミュニティのケアには、健全性の維持、コミュニティと参加者のレベル向上、組織におけるニーズを説くことが含まれます。

==== プロダクトオーナー

https://innersourcecommons.org/learn/learning-path/product-owner[_プロダクトオーナー_] の役割は、平均的なプロジェクトのプロダクトオーナーの役割と、いくつかの類似点があります。
しかし、プロジェクトのサイズによって違いがありますが、この役割はトラステッドコミッターとして行動する同じ人が担当することがよくあります。
大規模なプロジェクトや、貢献を受け容れることで彼らのニーズを満たす部分にだけInnerSourceのアプローチを用いるチームでは、この役割はトラステッドコミッターとは別の人が担当する可能性があります。

プロダクトオーナーの役割との対話では、あなたの貢献が一般的プロダクトとそのロードマップに適合するかに焦点を当てる可能性があります。
あなたはプロダクトオーナーの役割と協力して、あなたの貢献をマージする際に、ドキュメントやUI/UXの一貫性などの一般的な側面を確認することになります。

最後に重要なことですが、プロダクトオーナーとして行動している誰かは、プロジェクトやその利点およびコミュニティに対して、あなたの注目を引くことに関わっている可能性があります。

もし、これらの他の役割に関する詳細を学びたい場合は、 https://innersourcecommons.org/learn/learning-path/trusted-committer[_トラステッドコミッター_] と https://innersourcecommons.org/learn/learning-path/product-owner[_プロダクトオーナー_] のセクションを別に用意してありますので、そちらをお勧めします。

=== セクションの概要

これ以降の5つのセグメントで、ここで紹介したさまざまな側面について、詳しく学びます。

次のセグメントでは、 _InnerSource コントリビューターになる_ 機会を生みだす _マインドセットや習慣_ について詳しく説明します。

3番目のセグメントでは、 _コントリビューターの精神_ 、すなわち、あなたとホストチームにとって快適かつ生産的な時間につながり、より多くのコラボレーションを促進する可能性がある _行動_ の側面を見ていきます。
紹介ビデオで示したゲストインホームのアナロジーは、鮮明な例となるでしょう。

4番目のセグメントでは、あなたの貢献を成功させるための実践的なこと、つまり _貢献の仕組み_ について説明します。
貢献に取り組む準備をしていたり、開発をしたり、プルリクエストをしたりする時に活用する実用的なヒントを提供します。

コントリビューターの個人的、相互作用的、そして技術的な側面を扱った後に、5番目のセグメントでは、貢献するために努力することの効果について示します。
あなた、あなたのチーム、そして企業全体の視点など、さまざまな視点で効果があることを示します。

最後のセグメントでは、InnerSourceコントリビューターであるということについて学んだことをまとめます。
我々は、あなたが他のオンラインのビデオと記事の両方やオンラインのInnerSourceコミュニティへの参加を通じて、どのようにInnerSourceの学習を継続するかについて共有します。