[[upleveling]]
== Desenvolvendo Membros da Comunidade
Há uma participação contínua em uma comunidade InnerSource.
Há pessoas que não tem conhecimento da comunidade.
_Newcomers_ podem estar interessados na comunidade e seu produto, mas ainda não o usaram.
_Consumers_ usam o software, mas podem não ter feito uma contribuição
Depois, temos os https://innersourcecommons.org/learn/learning-path/contributor [_Contributors_] que fizeram pelo menos uma contribuição e, finalmente, os _Trusted Committers_, que estão assumindo a responsabilidade pelo software e pela comunidade.
Como um Trusted Committer, você é responsável por mover os indivíduos ao longo deste fluxo contínuo e desenvolver suas capacidades de fazer contribuições.
Nesse sentido, os Trusted Committers atuam como multiplicadores de força em sua comunidade.
É importante que os Trusted Committers façam o _marketing_ de seus produtos e comunidades para aumentar o número de _newcomers_ e consumidores.
Eles também devem comunicar aos consumidores as oportunidades para fazer contribuições e tentar obter e alinhar os interesses de potenciais https://innersourcecommons.org/learn/learning-path/contributor [_Contributors_] com os da comunidade.
O que geralmente funciona bem é se os https://innersourcecommons.org/learn/learning-path/contributor [_Contributors_] são capazes de trabalhar em algo que beneficie seu departamento ou função na empresa.
Ferramentas de desenvolvimento e automação são bons exemplos.
Por fim, é responsabilidade do Trusted Commiter identificar e apoiar https://innersourcecommons.org/learn/learning-path/contributor [_Contributors_] com potencial de crescimento, incentivando-os a enfrentar tarefas desafiadoras e orientá-los para a conclusão destas tarefas.
Esta é, em nossa opinião, a mais nobre responsabilidade de um Trusted Commiter, e é gratificante tanto para o Trusted Commiter como para o seu _Contributor_.
Ouvimos Trusted Committers dizer que orientar e ver as pessoas desenvolverem suas habilidades mais do que compensa o fato de que elas têm menos tempo para realmente gastar escrevendo software.
Conforme mencionado na https://innersourcecommons.org/learn/learning-path/trusted-committer/03 / [seção anterior], aprendizado e crescimento pessoal são razões pelas quais as pessoas se juntam e permanecem em uma comunidade InnerSource.
Desenvolver seus https://innersourcecommons.org/learn/learning-path/contributor [_Contributores_] é uma das ferramentas mais poderosas que os Trusted Commiters têm à disposição para aumentar a velocidade, a produção e a longevidade de suas comunidades.
Também é um dos principais argumentos para convencer a gerência a permitir que seus funcionários participem de uma comunidade InnerSource, pois isso tornará seus funcionários mais valiosos para a empresa em geral e os ajudará a reter os principais talentos.
Em resumo, os Trusted Commiters precisam atrair novos https://innersourcecommons.org/learn/learning-path/contributor [_Contributors_] e aumentar sua capacidade de fazer contribuições.
Esta atividade acaba por aumentar a capacidade da comunidade de criar software melhor mais rapidamente.
Eles fazem isso comunicando oportunidades para fazer contribuições e ajudando e orientando os _Contributors_, permitindo que eles cresçam.
