== Tornar-se um Trusted Committer
A função de Trusted Committer é uma função exigente, mas satisfatória.
Se este caminho de aprendizagem lhe interessa, você pode estar se perguntando como realmente se tornar um Trusted Committer e se você é a pessoa certa para o trabalho.
As comunidades InnerSource seguem os mesmos princípios que as comunidades Open Source, uma das quais é a meritocracia.
Em uma meritocracia, o poder é investido em indivíduos com base em talento, esforço e realizações.
Isso significa que o poder e os privilégios que vêm com o papel de Trusted Committer precisam ser conquistados.
A transparência, outro valor do Open Source, também desempenha um papel vital na medida em que torna o talento, o esforço e as conquistas visíveis para toda a comunidade.
O processo de se tornar oficialmente um Trusted Commiter difere de comunidade para comunidade, depende de onde você está em sua jornada InnerSource e pode evoluir ao longo do tempo.
Nas comunidades de base, os fundadores geralmente assumem o papel de Trusted Commiter. À medida que uma comunidade cresce, ou em comunidades maiores, os Trusted Commiters geralmente são nomeados ou votados pelos https://innersourcecommons.org/learn/learning-path/contributor[contributors] da comunidade.
Mas o papel do Trusted Commiter deve ser assumido voluntariamente, pois requer uma imensa quantidade de tempo e dedicação para ser bem-sucedido.
Quais são os critérios a serem aplicados na nomeação de https://innersourcecommons.org/learn/learning-path/contributor[contributors] para uma função de Trusted Commiter?
O que é necessário para preencher com sucesso o papel de um Trusted Commiter?
Em primeiro lugar, os potenciais Trusted Commiters devem ter demonstrado uma profunda competência técnica durante o seu trabalho na comunidade.
Além disso, eles devem ter comprovado sua capacidade de se comunicar efetivamente com os colegas da comunidade e, idealmente, também com os product owners e com a gestão.
Da mesma forma, eles devem ter demonstrado disposição e paciência para usar suas habilidades e dedicar seu tempo intencionalmente desenvolvendo os contribuidores.
Por fim, cumprir o papel de Trusted Committer requer certa maturidade emocional para lidar com situações sociais estressantes, que surgem de tempos em tempos.
Os Contributors que satisfazem esses critérios serão, em nossa opinião, bons Trusted Committers em potencial.
A função Trusted Committer pode não parecer tão atraente para alguns contributors, pois significa gastar menos tempo codificando.
Ser nomeado para o papel de Trusted Committer pode até ser percebido por alguns como um rebaixamento ou como feedback negativo sobre suas habilidades de codificação.
Mas, na verdade, é o oposto.
Ser nomeado para o papel de Trusted Committer geralmente significa que alguém reconheceu suas contribuições valiosas e vê em você o potencial de crescer e liderar.
A função Trusted Committer lhe dará mais influência sobre a evolução da base de código e, em última análise, fará de você um desenvolvedor mais completo.
Explicar aos contributors como o software funciona geralmente leva a novos insights por parte do Trusted Committer e ajudará a identificar oportunidades para melhorar o software..
Se você tem um ou vários Trusted Committers depende do tamanho e do risco associado ao software desenvolvido pela comunidade InnerSource.
A função Trusted Committer é demorada e nem todos estão dispostos ou aptos a assumir esse tipo de compromisso.
Por causa disso, algumas empresas utilizam um sistema rotativo de Trusted Commiter, em que vários Trusted Commiters partilham a carga de trabalho do papel de Trusted Commiter, e os Trusted Commiters que não estão em serviço podem se concentrar exclusivamente no trabalho orientado para a tecnologia.
Ter mais de um Trusted Committer também facilita quando alguém sai da empresa ou sai da função para fazer outra coisa.
Nesse caso, é importante que já existam outros Trusted Commiters, que possam assumir e assegurar a continuidade na comunidade.
Em resumo, o papel do Trusted Commiter tem de ser conquistato através de contribuições valiosas - tanto técnicas quanto sociais - em benefício da comunidade.
Em uma comunidade saudável, você terá outros Trusted Committers ao seu lado.
Como um Trusted Committer, você terá menos tempo para codificar, mas ao atuar como um multiplicador de força, você será capaz de aumentar sua contribuição de valor para a comunidade e acelerar seu próprio crescimento.
