== Conclusão
Nos capítulos anteriores, aprendemos sobre as responsabilidades dos comités de confiança.
Algumas dessas responsabilidades incluem garantir a qualidade do produto, manter sua comunidade saudável, reduzir as barreiras para fazer contribuições, levantar a comunidade e defender suas necessidades dentro da organização.
Também falamos sobre como se tornar um Comitê Confiável e o que é necessário para cumprir esse papel.
Trabalhar como um Trusted Committer é exigente, mas, em última instância, ampliará a sua contribuição de valor em sua empresa.
Esperamos tê-lo inspirado a partir de um caminho para se tornar um Trusted Committer. Também esperamos ter ajudado sua organização a entender a importância de ter Trusted Committers capazes para o sucesso de qualquer iniciativa InnerSource e o nível de empoderamento que esse papel requer.
Gostaríamos de convidá-lo a saber mais sobre o InnerSource explorando os outros artigos e vídeos no Caminho de Aprendizagem do InnerSource.
E, claro, gostaríamos de recebê-lo na comunidade do http://www.innersourcecommons.org/[the InnerSource Commons].
Que a fonte esteja com você.
