== Conclusion

In this learning path, we've given an introduction to InnerSource.
InnerSource applies open source best practices and principles to internal software development.
It gives an additional option to consumers when producing teams are not able to deliver a needed feature request.
Successful InnerSource involves a https://innersourcecommons.org/learn/learning-path/product-owner/01[_product owner_] and https://innersourcecommons.org/learn/learning-path/trusted-committer/01[_trusted committer_] from the *host team* as well as a https://innersourcecommons.org/learn/learning-path/contributor/01[_contributor_] from the *guest team*.
Done effectively, InnerSource brings many benefits to both participating teams.
They key principles upon-which effective InnerSource works are *voluntary code contribution* and *prioritized mentorship*.

While this training contains a high-level overview of InnerSource, there are many more details useful in making InnerSource actually work for your team.
If you want to stay connected to the ongoing conversation around InnerSource and its best practices, then join http://innersourcecommons.org[the InnerSource Commons].
The commons sponsors a Slack channel, an InnerSource patterns working group, and multiple in-person summits each year.
Participation in the commons is a great way to stay connected with the latest in InnerSource.
