== Cuáles son los beneficios de InnerSource?

Muchos son los beneficios de la colaboración a través de InnerSource.
InnerSource proporciona a la compañía una estrategia que _escala_ para *aquellos equipos que necesitan tener un nuevo requisito a tiempo* sin el problema de tener que mantenerlo en el tiempo.
Además, ésta es una situación donde la compañía gana como un todo ya que otros equipos tienen acceso a ese código.

Aunque éste sea uno de los beneficios más inmediatos y claros, hay muchos otros para aquellos que reciben contribuciones en este modelo de forma continua.
Como recordatorio y como parte del proceso InnerSource, el product owner del equipo que recibe las contribuciones está de acuerdo con esta contribución desde el principio, siendo éstas contribuciones esperadas y deseadas.
¡InnerSource permite al equipo anfitrión obtener *ayuda para crear un producto mejor* para sus consumidores!

*InnerSource proporciona una estrategia al equipo anfitrión que escala* para los diferentes requisitos que procedan de los diferentes consumidores a lo largo de la empresa.
Dada la capacidad limitada y fija de los miembros del equipo anfitrión, es probable que con el tiempo, la combinación de roadmaps de sus consumidores requieran una gran cantidad de trabajo, a veces inabarcable, en los diferentes productos.
Sin InnerSource, esta situación tendería fácilmente hacia un estrés continuo, equipos sobrecargados de trabajo y continuas peticiones de funcionalidades a través de la jerarquía.

Sin embargo, si el equipo anfitrión opera en un modelo InnerSource, las necesidades de personal y otros recursos requeridos para construir estas mejoras aparecerán en proporción a su importancia en la forma de contribuciones externas de otros equipos.
*InnerSource se convierte por lo tanto en una fuerza multiplicadora* que permite al equipo anfitrión abarcar más actividad que la que realmente puede llevar a cabo en épocas de alta demanda.
Cuando la demanda ha terminado, el equipo puede volver a su tamaño habitual sin necesidad de ningún tipo de microgestión.
InnerSource permite que el tiempo dedicado a ingeniería fluctúe acorde a las necesidades de la empresa en un momento dado.


Más allá del trabajo que el equipo anfitrión es capaz de llevar a cabo en su modo habitual, las contribuciones habituales en modo InnerSource da al equipo anfitrión *mejores requisitos y alineamiento de las prioridades de todos los consumidores*. Un equipo anfitrión puede hacer lo mejor que pueda esa recogida de requisitos, pero es cuando el consumidor participa cuando las probabilidades de que el cambio final esté alineado entre todos aumenten.
Aún cuando sólo haya un equipo enviando un cambio, ese equipo es probablemente una representación de otros consumidores.

Además de este alineamiento, hay un proceso de educación de los https://innersourcecommons.org/learn/learning-path/contributor[contribuidores] al trabajar y aprender con los https://innersourcecommons.org/learn/learning-path/trusted-committer[trusted committers].
Esta interacción ayuda a los contribuidores a aprender y evolucionar en su carrera profesional y esto conlleva una *mayor satisfacción del trabajo*.
La documentación del proyecto permite y mejora este tipo de contribuciones a escala.
Además, este tipo de procesos se recomiendan a otros colegas y a nuevos equipos para que se unan. Se comprende mejor al proyecto y son capaces de responder a preguntas a otros quitando parte del trabajo al equipo anfitrión.
Más personas contribuyendo a un proyecto desde diferentes áreas de la empresa ayuda a traer diferentes puntos de vista de forma natural.
Este tipo de enfoque de aprendizaje y alineamiento entre equipos permite a lo largo del tiempo *romper los silos que tradicionalmente existen en la empresa*.

