#Script: The Contributor in InnerSource - Introduction

=== Duration: 1-3 Mintes

=== Actors: Isabel and Johannes

=== Playbook Summary

This segment recaps what we've learned about being an InnerSource contributor.  We'll share how you can continue your learning on InnerSource both with with other online videos and also involvement with the online InnerSource community.

=== Script

J:: Thanks for watching the Contributor segment of the InnerSource Commons Learning Path. With this section you've learned about the Contributor role - the life blood of InnerSource projects: External to the owners of a component's team, they bring additional valuable input to the project.

I: You've learned about how to become an contributor by looking for opportunities to contribute as well as the mindset and habits needed to find or create such opportunities.
We've also discussed the ethos of the role and suggested some behaviour that is likely to lead to successful contributions.

J: Given the right mindset, habits and ethos there are still a few details that might keep you from successfully contributing - hence, we've discussed these nuts and bolts in greater detail.

I: Last but not least, convincing your teammates and your organization at various levels can be hard, thus we've discussed the benefits of contribution from various perspectives to make this process easier for you.

J: We hope you've enjoyed watching the videos and reading the articles. We hope you could take away some interesting new insights for your journey towards InnerSource and being a good contributor.

I: If you haven't done so already, we would like to invite you to also learn more about the other aspects of InnerSource in our InnerSource learning path: http://innersourcecommons.org/learningpath/

\-> Show link overlay.

Be welcome to additionally check out the InnerSource group http://innersourcecommons.org[InnerSource Commons] online!
Feel free to join the discussion and share your experiences and lessons learnt.

\-> Show link overlay. Special customized overlay a la innersourcecomms.org/invite that we could then map to the Slack inviter or elsewhere or just the blank domain?

J: Live long and have prosperous projects!
