== InnerSourceの効果とは？

InnerSourceによるコラボレーションには、多くの効果があります。
InnerSourceは、ゲストチームが長期メンテナンスの負担をせず、 *彼らが必要な時に機能要求を手に入れる* ためのスケーラブルな戦略を企業に提供します。
ゲストチームの時間を、他の人たちが利用できるコードに投入することが、会社全体としての勝利へとつながります。

この結果はInnerSourceの優れた効果であると同時に、定常的にInnerSourceのコントリビューションを受け取るホストにも多くの効果があります。
InnerSourceのプロセスの一部には、ホストチームのプロダクトオーナーが、コントリビューションされた機能が正しくかつ望まれたものであることに、最初から同意していることを思い出してください。
InnerSourceは、それを利用する人達のために *良いプロダクトを作るための支援* をホストチームが受け取ることを可能にします!

*InnerSourceはホストチームにスケーラブルな戦略を提供し* 、多くの利用者たちからの、さまざまな機能要求に応えてゆくことが可能となります。
ホストチームのフルタイムメンバーの対応力が固定されているとした場合、時として、その利用者たちのビジネスロードマップの組み合せが、ホストチームの製品で非常に（または理不尽に）大量の作業を必要とすることにつながる可能性があります。
InnerSourceなしでは、こうした状況は、リーダーにエスカレーションされた多くの機能要求に対処する、過労とストレスに満ちたチームを簡単に生みだすことにつながります。

しかし、もしホストチームがInnerSourceにより運営している場合、それらの機能を構築するために必要なエンジニアリソースは、それらの重要度に応じたゲストコントリビューターの形で現れます。
*InnerSourceは、フォースマルチプライヤーになり* 、需要が高い時間帯に、ホストチームが一時的に実際のサイズよりも大きく行動することを可能とします。
需要が終了すると、チーム人員や作業項目に関するマイクロマネージメントを一切せずとも、チームのスループットは通常のレベルに戻ります。
InnerSourceは、組織が必要とする時と場所にエンジニアリングの時間を有機的に投入することを可能とします。

ホストチームがそのシステムで本来達成可能な作業を超えて、InnerSourceの定期的な貢献により、ホストチームは *全ての利用者とのより良い要件と優先順位の調整を行うことができます* 。
ホストチームは、作成した作業について最高の要件収集を行うことができますが、利用者自信が作業を提出する場合、結果として、行われた変更が利用者のニーズと合致する可能性がはるかに高くなります。
変更を提出しているのは、1つのゲストチームだけかもしれませんが、そのチームが他の多くの利用者を代表している可能性があります。

こうした調整に加えて、 https://innersourcecommons.org/ja/learn/learning-path/contributor[コントリビューター] が https://innersourcecommons.org/ja/learn/learning-path/trusted-committer[Trusted Committer] と一緒に働き、そこから学ぶことは、一般的なトレーニングや教育にもなります。
こうした対話は、コントリビューターのキャリア形成における成長や学習に寄与し、結果として *仕事への満足度が高くなります* 。
プロジェクトのドキュメントは、大規模なコントリビューションを可能にするために改善されます。
コントリビューターは、ホストチームのプロジェクトとの一体感を感じます。
それは、コントリビューターが、彼らの同僚や新しいチームに参加を推奨するものです。
彼らはプロジェクトをより理解し、プロジェクトに関する質問に対して他の人に答えることかできるようになり、ホストチームの負担を軽減します。
プロジェクトに貢献する人が増えると、会社全体からのアイデアが自然に融合し生まれます。
このような学習とチーム間連携は、時間を経て *従来の会社のサイロをなくすことに役立ちます* 。
