:doctype: book

このドキュメントの目的は、このラーニングパスの紹介セグメントの内容に関係する補足と計画資料を保持することです。

== 目的

このラーニングパスセグメントは、InnerSourceを紹介するシリーズの最初のものです。
このラーニングパスは、InnerSourceに関して現在の公な会話の焦点と共有コンテキストとならなければなりません。
この目的を達成すつために、この紹介では次のものを提供しなければなりません：

* 5つのキータームに関しての明確かつ説得力のある定義:
 ** ホスト (チーム)
 ** ゲスト (チーム)
 ** トラステッドコミッター
 ** プロダクトオーナー
 ** コントリビューター
* InnerSourceを最低限実行可能とするための補助レール:
 ** 自発的なコードコントリビューション
 ** 優先的なメンターシップ
* 視聴者が残りのラーニングパスセグメント視聴のための関心と期待

== 対象者（視聴者・読者）

InnerSourceについて聞いたことがある人であれば誰でも、このラーニングパスの対象者です。

== アウトライン

=== はじめに

トピック、その重要性の理由、そして視聴者がこのラーニングパスから何を学ぶかを紹介します。

=== 位置合わせ

仮定の（とは言え、まだ信じられる）例として、既存のプロセスで組織のサイロ横断で連携する難しさを示して共有します。
この与えられた状況は、このラーニングパスを通して、特に、5つのキータームの紹介をする時と、InnerSourceに関する誤解を防ぐ時に参照する基礎となります。

=== 解決策

例示した状況で、プレイヤーが困難を克服するために、どのようにInnerSourceを通してコラボレーションができるかを示します。
このアプローチの利点を示します。
この説明をする際には、5つのキータームに関する明確な定義と、InnerSourceに関する誤解を防ぐために特別にデザインされた表現も自然に含めます。

=== 詳細の説明

InnerSourceのプロセスについて、幾つか "`落とし穴`" となるポイントについて掘り下げます。
メッセージの主要な部分をさらに固めるために、短く説得力のある逸話を戦略的に用いることを検討します。
このセクションに含まれる傾向がある資料は、さらにInnerSourceへの誤解を払拭し、このラーニングパスの次のセグメントのための準備をするものです。

=== おわりに

このラーニングパスの主要なポイントを確認し、視聴者が次のセグメントに期待するように設定します。
興味ある視聴者が、InnerSourceコモンズ参加するように招待します。
