const fs = require('fs')
const YAML = require('yaml')
const { EOL } = require('os')

module.exports = writeMarkdownFile = (filePath, frontMatter, body) => {
  const frontMatterTerminator = '---'
  const originStatement = '<!--- This file autogenerated from https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/main/scripts -->'
  const output = [frontMatterTerminator, YAML.stringify(frontMatter).trim(), frontMatterTerminator, body, originStatement].filter(item => !!item).join(EOL)
  fs.writeFileSync(filePath, output)
}
