import fs from 'fs'
import YAML from 'yaml'
import { EOL } from 'os'

export default function (filePath, frontMatter, body) {
  const frontMatterTerminator = '---'
  const originStatement = '<!--- This file autogenerated from https://github.com/InnerSourceCommons/InnerSourceLearningPath/blob/main/scripts -->'
  const output = [frontMatterTerminator, YAML.stringify(frontMatter).trim(), frontMatterTerminator, body, originStatement].filter(item => !!item).join(EOL)
  fs.writeFileSync(filePath, output)
}
