:doctype: book

The purpose of this document is the hold the supplementary and planning material related to the content of the introductory segments of this learning path.

== Goals

These learning path segments are the first in a series introducing InnerSource.
This learning path should be the focal point and shared context of the current public conversation around InnerSource.
In order to achieve that goal, this introduction must provide:

* Compelling and clear definitions around 5 key terms:
 ** Host (team)
 ** Guest (team)
 ** Trusted Committer
 ** Product Owner
 ** Contributor
* Guardrails for the minimum viable attributes of InnerSource:
 ** Voluntary Code Contribution
 ** Prioritized Mentorship
* Interest and anticipation for viewers to watch the remaining learning path segments

== Audience

The audience for this learning path is anyone that has heard of InnerSource.

== Outline

=== Introduction

Introduce the topic, why it's important, and what the viewer will learn in this learning path.

=== Justification

Share a hypothetical (yet believable) example situation that illustrates the difficulties today in the off-the-shelf process of collaborating across organizational silos.
This given situation will be the basis to-which we refer throughout the learning path, most notably when introducing the 5 key terms and heading off misconceptions about InnerSource.

=== Solution

Show how the players in the example situation can collaborate via InnerSource to overcome their difficulty.
Explain the benefits of this approach.
While giving this explanation, naturally include clear definitions of the 5 key terms and also wording specifically designed to dispel misconceptions about InnerSource.

=== Further Explanation

Delve into some "`gotchas`" and more nuanced points about the InnerSource process.
Consider strategic use of short and compelling anecdotes to cement key parts of the message further.
Trend towards including material in this section that further dispels InnerSource misconceptions and also sets the stage for the upcoming segments in the learning path.

=== Conclusion

Review the key points of this learning path and tee up viewers to look for the next segments.
Invite interested viewers to participate in the InnerSource Commons.

=== 提纲
本文档的目的是保存与本教程学习路径的导论部分内容的相关补充和计划材料。

=== 目标
这些学习路径章节是介绍InnerSource的系列文章的第一部分。本教程学习路径应该成为当前围绕InnerSource的核心公共焦点，同时共享上下文。为了实现这一目标，这一导言必须提供：

* 令人信服的和定义明确的5个关键术语:
 ** 主人(团队)
 ** 客人(团队)
 ** 受信任提交者
 ** 产品所有者
 ** 贡献者
 
* InnerSource中最小可行性的防护机制:
 ** 自愿贡献
 ** 优先辅导
 
* 吸引和引导观众参与观看剩余的学习路径章节

=== 观众
本课程学习路径的听众是任何听说过InnerSource的人。

=== 介绍
介绍主题和InnerSource的重要性，以及观众在学习过程中将学到什么。

=== 理由
共享一个假设的（但可信任的）示例情形，该情形说明了当前跨组织壁垒协作的形成的流程中的困难。这种设定的情形将是我们在整个学习过程中引用的基础，特别是在介绍5个关键术语和消除对内部资源的误解时有效。

=== 解决方案
展示例子中的角色如何通过InnerSource进行协作来克服他们的困难。解释这种方法的好处。在给出这个解释的同时，自然要包括对这5个关键术语的明确定义，以及专门用来消除对内部来源误解的措辞。

=== 进一步阐述
深入研究关于InnerSource过程的一些“陷阱”和更微妙的观点。考虑使用简短而引人注目的例子来进一步巩固信息的关键部分。在本节中包含材料的趋势进一步消除了内部来源的误解，并为学习路径中即将出现的部分奠定了基础。

=== 结论
回顾这条学习路径的关键点，引导观众寻找下一个片段。邀请有兴趣的观众可加入InnerSource社区。


