== Garder la communauté en bonne santé

L'introduction a souligné que les Trusted Committers ont des responsabilités à la fois axées sur la technologie et sur la collectivité.
Il ne suffit pas de se concentrer uniquement sur le code et la santé du code. Pour assurer le succès à long terme, les Trusted Committers devraient s'efforcer de maintenir la communauté qui construit le logiciel en bonne santé. Pour cette raison, ils doivent trouver un bon équilibre entre la garantie de la qualité des produits et la croissance d'une communauté en bonne santé.

À quoi ressemble une communauté en santé? Tout simplement, dans une communauté en bonne santé, https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] ont tendance à rester, peuvent passer la plupart de leur temps à développer des logiciels et sont capable d'améliorer leur capacités. Par conséquent, une collectivité en santé ne cesse de croître.

Pourquoi https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] se joint-t-ils et reste-t-ils dans une communauté? Certains le font parce qu'ils souscrivent à l'objectif ou à la mission de la communauté. Le travail du Trusted Committer consiste à formuler et à promouvoir clairement cet objectif. L'importance de ce fait n'est souvent pas reconnue, mais la commercialisation d'une communauté et de ses produits est vraiment essentielle.

Une autre raison, plus évidente pour que les gens restent dans la communauté est qu'ils aiment travailler avec d'autres membres de la communauté, y compris les Trusted Committers. Une communauté florissante est une communauté où les membres traitent et communiquent les uns avec les autres avec le plus grand respect. Les contributions sont traitées comme des cadeaux ou des dons plutôt que des distractions, et les excellentes contributions (surtout les premières) sont louées. Le travail du Trusted Committer dans tout cela consiste principalement à définir un exemple pour les autres, similaire à la définition d'un exemple pour le niveau de qualité de logiciel attendu. Si nécessaire, les Trusted Committers sont ceux qui devraient créer et promulguer un code de conduite pour la communauté. S'il y a des membres de la communauté dont le comportement est préjudiciable ou toxique pour la santé de la communauté, il est de la responsabilité du Trusted Committer d'aborder le probleme. Les Trusted Committers devraient créer des occasions pour les gens de se réunir régulièrement (en personne ou virtuellement), de se connaître personnellement et de résoudre pacifiquement les conflits au fur et à mesure qu'ils surviennent.

Les gens ont également tendance à rester dans une communauté parce que travailler dans une communauté InnerSource est une excellente occasion d'acquérir de nouvelles compétences et de se développer personnellement. C'est là encore que le rôle du Trusted Committer est vraiment important. Les Trusted Committers deviennent souvent des mentors pour les développeurs débutants, et passent explicitement du temps pendant les pull requests, non seulement en soulignant les domaines à améliorer, mais aussi en expliquant en détail pourquoi quelque chose doit être amélioré et comment le faire. Ils fournissent la théorie ou l'expérience derrière le changement et offrent des suggestions pour les meilleurs moyens de le mettre en œuvre. Ce faisant, les Trusted Committers peuvent augmenter la vitesse d'apprentissage dans leurs communautés bien au-delà de celle des projets de développement de logiciels traditionnels.

Nous croyons que les Trusted Committers devraient accorder la priorité à l'intégration et au mentorat lors des pull requests plutôt qu'à l'atteinte des dates de sortie communiquées, à moins qu'il n'y ait une très bonne raison de ne pas le faire. Un bon mentorat lors des pull requests conduit à un niveau plus élevé de confiance et d'engagement de la part des https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_], ce qui entraîne à son tour davantage de contributions. Nous en discuterons plus en détail dans https://innersourcecommons.org/learn/learning-path/trusted-committer/04/["Upleveling the Community" ].

Enfin, certaines personnes restent dans les communautés d'InnerSource parce qu'elles se concentrent sur le développement de logiciels au lieu d'activités considérées comme des frais généraux ou des perte de temps, en particulier dans les grandes entreprises qui mettent l'accent sur les processus. Dans ce contexte, le travail du Trusted Committer consiste à s'assurer que https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] peuvent réellement se concentrer sur leurs projets en communiquant et en adoptant des instructions de contribution utiles.

L'un des aspects importants de ces lignes directrices est d'expliquer ce que nous appelons signaling durant les pull requests: à quoi devrait ressembler un commentaire? Qu'est-ce que cela signifie si je like ou +1 un commentaire? En quoi @mentioning quelqu'un avec un préfixe /CC diffère-t-il de l'utilisation d'un préfixe /FYI? En règle générale, les Trusted Committers doivent s'assurer que le processus de contribution ne crée pas plus de problèmes, mais qu'il aide la communauté à identifier et à résoudre les problèmes. En fin de compte, les Trusted Committers devraient habiliter leur communauté à trouver des problèmes liés aux processus, à les adapter et à les améliorer autant que possible en tant que communauté.

Pour que les Trusted Committers puissent s'acquitter de toutes ces responsabilités, il est important qu'ils communiquent régulièrement avec les membres de la communauté et qu'ils soient à l'écoute du terrain. Nous allons plus de détails à ce sujet dans la section https://innersourcecommons.org/learn/learning-path/trusted-committer/06/["Advocating the Community's Needs" ].

En résumé, les Trusted Committers devraient s'efforcer de créer un environnement accueillant et apprécié pour leur https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] qui leur permettent de se concentrer sur la rédaction de logiciels et de se développer personnellement en créant des occasions d'apprendre des autres membres de la communauté.
