== Devenir un comité de confiance
Le rôle de "Trusted Committer" est un rôle exigeant mais satisfaisant. Si ce parcours d'apprentissage vous intéresse, vous pourriez vous demander comment devenir un comité de confiance et si vous êtes la bonne personne pour le travail.

Les communautés InnerSource suivent les mêmes principes que les communautés Open Source, dont l'un est la méritocratie. Dans une méritocratie, le pouvoir est dévolu à des individus en fonction du talent, de l'effort et des réalisations.
Cela signifie que le pouvoir et les privilèges associés au rôle de valideur de confiance doivent être acquis.
La transparence, autre valeur de l'Open Source, joue également un rôle essentiel dans la mesure où elle rend les talents, les efforts et les réalisations visibles pour l'ensemble de la communauté.

Le processus de devenir officiellement un "Trusted Committer" diffère d'une communauté à l'autre, dépend de l'endroit où vous vous trouvez dans votre parcours InnerSource et peut évoluer au fil du temps.
Dans les communautés de base, les fondateurs assument souvent le rôle de "Trusted Committer". Au fur et à mesure de la croissance d'une communauté, ou dans les communautés plus grandes, les "Trusted Committers" sont généralement nommés ou votés par la communauté https://innersourcecommons.org/learn/learning-path/contributor [ contributeurs ].
Mais le rôle de "Trusted Committer" devrait être assumé volontairement, car il faut énormément de temps et de dévouement pour réussir dans ce domaine.

Quels sont les critères à appliquer lors de la nomination de https://innersourcecommons.org/learn/learning-path/contributor[contributors] pour un rôle de valideur de confiance? Que faut-il pour remplir avec succès le rôle d'un comité de confiance?
Tout d'abord, les comités de confiance potentiels doivent avoir démontré une compétence technique approfondie au cours de leur travail au sein de la communauté.

En outre, ils doivent avoir prouvé leur capacité à communiquer efficacement avec les pairs de la communauté et, idéalement, aussi avec les propriétaires de produits et avec la direction.
Dans le même ordre d'idées, ils doivent avoir fait preuve de la volonté et de la patience d'utiliser leurs compétences et de passer du temps intentionnel à faire des contributions.
Enfin, pour remplir le rôle de "Trusted Committer", il faut une certaine maturité émotionnelle pour faire face à des situations sociales stressantes, qui ne manquera pas de se présenter de temps à autre.
Les contributeurs qui satisfont à ces critères seront, à notre avis, de bons potentiels pour les comités de confiance.

Il se peut que le rôle de valideur de confiance ne soit pas aussi attrayant pour certains contributeurs, car cela signifie passer moins de temps à coder.
Être nommé pour le rôle de "Trusted Committer" peut même être perçu par certains comme une rétrogradation ou comme une rétroaction négative sur leurs compétences en codage.
Mais le contraire est vrai.

Être nominé pour le rôle de "Trusted Committer" signifie généralement que quelqu'un a reconnu vos précieuses contributions et voit en vous le potentiel de croître et de diriger.
Le rôle de Trusted Committer vous donnera plus d'influence sur l'évolution du codebase et vous rendra en fin de compte un développeur plus complet.
Expliquer aux contributeurs comment le logiciel fonctionne le plus souvent conduit à de nouveaux éclairages sur une partie du comité de confiance et aidera à identifier les opportunités d'amélioration du logiciel.

La présence d'un ou de plusieurs valideurs de confiance dépend de la taille et du risque associés au logiciel développé par la communauté InnerSource.
Le rôle de valideur de confiance prend beaucoup de temps et tout le monde n'est pas disposé ou en mesure de faire ce type d'engagement.
Pour cette raison, certaines entreprises utilisent un système de rotation des comités de confiance dans lequel plusieurs comités de confiance partagent la charge de travail du rôle de comité de confiance et les comités de confiance qui ne sont pas de service peuvent se concentrer exclusivement sur le travail axé sur la technologie.
Le fait d'avoir plus d'un valideur de confiance facilite également la tâche lorsqu'une personne quitte l'entreprise ou quitte son rôle pour faire quelque chose d'autre.
Dans ce cas, il est important qu'il existe déjà d'autres comités de confiance, qui peuvent prendre le relais et assurer la continuité dans la communauté.

En résumé, le rôle de "Trusted Committer" doit être gagné en apportant des contributions précieuses-à la fois techniques et sociales-au bénéfice de la communauté.
Dans une communauté en bonne santé, vous aurez des collègues de confiance à vos côtés. En tant que Comité de confiance, vous aurez moins de temps à coder, mais en agissant comme multiplicateur de force, vous serez en fin de compte en mesure de stimuler votre contribution de valeur à la communauté et d'accélérer votre propre croissance.
