== Conclusion

Dans ce parcours d'apprentissage, nous avons proposé une introduction à l'InnerSource.
L'InnerSource applique les meilleures pratiques et les principes de l'open source au développement de logiciels internes.

Il offre une option supplémentaire aux consommateurs lorsque les équipes de production ne sont pas en mesure de fournir une demande de fonctionnalité nécessaire.
Un projet InnerSource réussi implique un https://innersourcecommons.org/learn/learning-path/product-owner/01[_product owner_] et un https://innersourcecommons.org/learn/learning-path/trusted-committer/01[_trusted committer_] de l'équipe *hôte* ainsi qu'un https://innersourcecommons.org/learn/learning-path/contributor/01[_contributor_] de l'équipe *invitée*.
Réalisée efficacement, l'InnerSource apporte de nombreux avantages aux deux équipes participantes.
Les principes clés sur lesquels repose l'efficacité d'InnerSource sont la *contribution volontaire au code* et le *mentorat hiérarchisé*.

Bien que cette formation donne un aperçu de haut niveau de l'InnerSource, il existe de nombreux autres détails utiles pour faire fonctionner l'InnerSource avec votre équipe.
Si vous souhaitez rester connecté à la conversation en cours autour de l'InnerSource et de ses meilleures pratiques, alors rejoignez http://innersourcecommons.org [the InnerSource Commons].
L'Innersource commons sponsorise un canal Slack, un groupe de travail sur les modèles InnerSource, et plusieurs rencontres en physique chaque année.
La participation au groupe Innnersource commons est un excellent moyen de rester connecté avec les dernières nouveautés de l'InnerSource.
