
[[upleveling]]
== Aggiornamento dei membri della comunità

VI è un continua partecipazione della comunità InnerSource. Vi sono persone che non sono a conoscenza della comunità. _Newcomers_ le quali potrebbero essere interessate alla comunità ed al prodotto, ma non lo hanno ancora utilizzato. _Consumers_ utilizzano il software ma potrebbero non aver apportato un contributo. Poi vi sono i https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] che hanno dato almeno un contributo, ed infine i _Trusted Committers_, che si prendono la responsabilità sia del software che della comunità. In qualità di Trusted Committer, si è responsabile di educare le persone lungo questo percorso e migliorare la loro capacità di dare  ontribute. In tal senso, i Trusted Committers agiscono come moltiplicatori di forza nella loro comunità.

È importante che i Trusted Committers sponsorizzano i propri prodotti e le proprie comunità per aumentare il numero di newcomers e consumatori. Inoltre, dovrebbero comunicare le opportunità di dare  ontribute ai consumatori e cercare di suscitare ed allineare gli interessi di potenziali https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] con quelli della comunità. Si è visto che funziona bene si quandp i https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] sono in grado di lavorare su qualcosa che beneficia il propio reparto o ruolo in azienda. Buoni esempi sono gli strumenti di sviluppo e l'automazione..

Infine, è responsabilità del Trusted Committer identificare e sostenere i https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] con potenziale di crescita, incoraggiandoli ad affrontare compiti impegnativi ed ad orientarli verso il loro completamento. Questa è, a nostro parere, la più nobile responsabilità dei Trusted Committer, ed è gratificante sia per Trusted Committer che per i Contributors. Trusted Committers preferiscono fare da mentore e vedere le persone migliorare le loro capacità piuttosto che scrivere software dato il poco tempo a disposizione.

Come menzionato nella sezione https://innersourcecommons.org/learn/learning-path/trusted-committer/03/[previous], l'apprendimento e la crescita personale sono i motivi per cui le persone si uniscono e si aggirano in una community InnerSource. Lo sviluppo dei loro https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] è uno degli strumenti più potenti che Trusted Committers ha a disposizione per aumentare la velocità, la produzione e la longevità delle loro comunità. È anche uno degli argomenti chiave con cui convincere i dirigenti a consentire ai loro dipendenti di partecipare a una comunità InnerSource, in quanto ciò renderà i loro dipendenti più preziosi per l'azienda ed in generale li aiuterà a mantenere i migliori talenti.

In conclusione, i Trusted Committers devono attrarre nuovi https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] ed aumentare la loro capacità di dare contributi. Questa attività alla fine aumenta la capacità della comunità di creare software migliori più velocemente. Lo fanno comunicando opportunità di dare contributi ed aiutando e facendo da mentore ai Contributors che consentono loro di crescere.

