[ [ upleveling]]
== Aggiornamento dei membri della comunità
C'è un continuum di partecipazione in una comunità InnerSource. Ci sono persone che non sono a conoscenza della comunità. _Newcomers_ potrebbe essere interessato alla comunità e al prodotto, ma non lo ha ancora utilizzato. _Consumers_ utilizza il software ma potrebbe non aver apportato un contributo. Poi ci sono i https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] che hanno dato almeno un contributo, e infine i _Trusted Committers_, che si stanno prendendo la responsabilità sia del software che della comunità. In qualità di Trusted Committer, sei responsabile di spostare le persone lungo questo continuum e migliorare la loro capacità di dare contributi.

In questo senso, i Trusted Committers agiscono come moltiplicatori di forza nella loro comunità. È importante che i Trusted Committers commercializzino i propri prodotti e le proprie comunità per aumentare il numero di nuovi arrivati e di consumatori. Dovrebbero anche comunicare le opportunità di dare contributi ai consumatori e cercare di suscitare e allineare gli interessi del potenziale https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] con quelli della comunità. Ciò che spesso funziona bene è se https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] è in grado di lavorare su qualcosa che avvantaggia il loro reparto o ruolo in azienda. Gli strumenti di sviluppo e l'automazione sono buoni esempi.

Infine, è responsabilità del Trusted Committer identificare e sostenere https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] con il potenziale di crescere incoraggiandoli ad affrontare compiti impegnativi e a orientarli verso il completamento. Questa è, a nostro parere, la più nobile responsabilità del Trusted Committer, ed è gratificante sia per Trusted Committer che per il suo contributo. Abbiamo sentito i Trusted Committers dire che fare da mentore e vedere le persone aumentare le loro capacità più che rifarsi al fatto che hanno meno tempo per scrivere software.

Come menzionato nella sezione https://innersourcecommons.org/learn/learning-path/trusted-committer/03/[previous], l'apprendimento e la crescita personale sono i motivi per cui le persone si uniscono e si aggirano in una community InnerSource. Upleveling loro https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] è uno degli strumenti più potenti che Trusted Committers ha a disposizione per aumentare la velocità, la produzione e la longevità delle loro comunità. È anche uno degli argomenti chiave con cui convincere i dirigenti a consentire ai loro dipendenti di partecipare a una comunità InnerSource, in quanto ciò renderà i loro dipendenti più preziosi per l'azienda in generale e li aiuterà a mantenere i migliori talenti.

In sintesi, i Trusted Committers devono attrarre nuovi https://innersourcecommons.org/learn/learning-path/contributor[_Contributors_] e aumentare la loro capacità di dare contributi. Questa attività alla fine aumenta la capacità della comunità di creare software migliori più velocemente. Lo fanno comunicando opportunità di dare contributi e aiutando e facendo da mentore ai Contributori che consentono loro di crescere.
